// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-beta.1 (IR schema 2, runtime 0.1.0-beta.1)
// Source SDK: Apple SDK fixture
// Derived from SDK metadata installed on the build machine; see
// docs/legal/source-provenance.md before redistributing.

/// Umbrella library for the generated Apple bindings. Import with a
/// prefix (e.g. `as ios`): Objective-C and Flutter share type names.
library;

export 'apple/nabfixtures.dart';
export 'apple/_runtime.dart' show NativeObjCError, NativeThreadingError, isMainThread, nsDataView, nsDataFromBytes;
