import 'package:native_api_ir/native_api_ir.dart';

/// Objective-C classes, protocols and structs that `package:objective_c`
/// already provides (generated by the Dart team's ffigen from Foundation).
/// Generated code references them (`objc.NSString`) instead of redefining
/// them, like the Android target uses `JString`/`JObject` from package:jni.
const objectiveCRuntimeTypes = {
  'NSArray', 'NSAttributedString', 'NSBundle', 'NSCharacterSet', 'NSCoder',
  'NSData', 'NSDate', 'NSDictionary', 'NSEnumerator', 'NSError', 'NSIndexSet',
  'NSInputStream', 'NSInvocation', 'NSItemProvider', 'NSLocale',
  'NSMethodSignature', 'NSMutableArray', 'NSMutableData',
  'NSMutableDictionary', 'NSMutableIndexSet', 'NSMutableOrderedSet',
  'NSMutableSet', 'NSMutableString', 'NSNotification', 'NSNull', 'NSNumber',
  'NSObject', 'NSOrderedCollectionChange', 'NSOrderedCollectionDifference',
  'NSOrderedSet', 'NSOutputStream', 'NSPort', 'NSPortMessage', 'NSProgress',
  'NSRunLoop', 'NSSet', 'NSStream', 'NSString', 'NSTimer', 'NSURL',
  'NSURLHandle', 'NSValue', 'Protocol',
  // Protocols.
  'NSCoding', 'NSCopying', 'NSFastEnumeration', 'NSItemProviderReading',
  'NSItemProviderWriting', 'NSMutableCopying', 'NSObjectProtocol',
  'NSPortDelegate', 'NSSecureCoding', 'NSStreamDelegate',
  // Structs.
  'NSRange', 'NSFastEnumerationState', 'NSEdgeInsets',
};

/// Whether [id] (e.g. `Foundation.NSString`) is provided by package:objective_c.
bool isRuntimeProvided(String id) {
  final i = id.indexOf('.');
  if (i < 0) return false;
  final module = id.substring(0, i);
  return (module == 'Foundation' || module == 'ObjectiveC') &&
      objectiveCRuntimeTypes.contains(id.substring(i + 1));
}

/// Whether [t] is a Cocoa `NSError **` out-parameter (mapped to a thrown
/// `NativeObjCError` instead of a raw pointer).
bool isErrorOutParameter(TypeRef t) =>
    t is PointerTypeRef &&
    t.pointee is DeclaredTypeRef &&
    (t.pointee as DeclaredTypeRef).name == 'Foundation.NSError';

/// Target-capability analysis for Dart over `package:objective_c`.
ApiModule planDartObjC(ApiModule module) {
  final generated = {
    for (final t in module.types)
      if (t.isGeneratable) t.id,
  };

  // Value types (structs) that cannot be laid out, e.g. bit-field structs:
  // passing them by value is impossible without a native shim.
  final opaqueStructs = {
    for (final t in module.types)
      if (t.kind == TypeKind.struct && !t.isGeneratable) t.id,
  };

  Diagnostic d(
    DiagnosticCode c,
    String id,
    String msg, [
    Severity s = Severity.warning,
  ]) => Diagnostic(c, msg, symbolId: id, severity: s);

  // Returns an unsupported reason for a type used in a signature, or null.
  String? unsupportedReason(TypeRef t) => switch (t) {
    BlockTypeRef() => 'E004',
    ArrayTypeRef() => 'E002',
    DeclaredTypeRef(:final name)
        when name == 'objc.unsupported' ||
            name == 'objc.Class' ||
            name == 'objc.SEL' =>
      'E002',
    DeclaredTypeRef(:final name) when opaqueStructs.contains(name) => 'E002',
    PointerTypeRef(:final pointee) => switch (pointee) {
      BlockTypeRef() => 'E004',
      _ => null,
    },
    _ => null,
  };

  final types = <ApiType>[];
  for (final t in module.types) {
    if (!t.isGeneratable) {
      types.add(t);
      continue;
    }
    final methods = <ApiMethod>[];
    for (final m in t.methods) {
      if (!m.isGeneratable) {
        methods.add(m);
        continue;
      }
      final extra = <Diagnostic>[];
      Diagnostic? blocked;
      for (final ty in [m.returnType, for (final p in m.parameters) p.type]) {
        final r = unsupportedReason(ty);
        if (r == 'E004') {
          blocked ??= d(
            DiagnosticCode.unsupportedCallback,
            m.id,
            'Objective-C blocks are not supported by the Flutter iOS target yet (needs native trampolines)',
          );
        } else if (r == 'E002') {
          blocked ??= d(
            DiagnosticCode.unsupportedType,
            m.id,
            'Unsupported type ${ty.display}',
          );
        }
        if (ty is PointerTypeRef && !isErrorOutParameter(ty)) {
          extra.add(
            d(
              DiagnosticCode.unsupportedType,
              m.id,
              'Raw C pointer ${ty.display}: exposed as ffi.Pointer (unsafe)',
              Severity.info,
            ),
          );
        }
        for (final n in ty.referencedTypes) {
          if (!n.startsWith('objc.') &&
              !generated.contains(n) &&
              !isRuntimeProvided(n)) {
            extra.add(
              d(
                DiagnosticCode.outsideClosure,
                m.id,
                'Outside the generation closure, exposed as ObjCObject: $n',
                Severity.info,
              ),
            );
          }
        }
      }
      final support = blocked != null
          ? SupportStatus.unsupported
          : extra.isEmpty
          ? m.support
          : SupportStatus.partial;
      methods.add(
        ApiMethod(
          id: m.id,
          name: m.name,
          kind: m.kind,
          returnType: m.returnType,
          parameters: m.parameters,
          typeParameters: m.typeParameters,
          throws: m.throws,
          threading: m.threading,
          permissions: m.permissions,
          asyncKind: m.asyncKind,
          nativeDescriptor: m.nativeDescriptor,
          modifiers: m.modifiers,
          annotations: m.annotations,
          availability: m.availability,
          visibility: m.visibility,
          support: support,
          documentation: m.documentation,
          diagnostics: [...m.diagnostics, ?blocked, ...extra.toSet()],
        ),
      );
    }
    final typeDiags = <Diagnostic>[
      if (t.kind == TypeKind.protocol)
        d(
          DiagnosticCode.unsupportedCallback,
          t.id,
          'Implementing Objective-C protocols in Dart is not supported by the Flutter iOS target yet; the protocol is usable for typing and calling',
          Severity.info,
        ),
      if (isRuntimeProvided(t.id))
        d(
          DiagnosticCode.outsideClosure,
          t.id,
          'Provided by package:objective_c (referenced, not regenerated)',
          Severity.info,
        ),
    ];
    types.add(
      t.copyWith(
        methods: methods,
        diagnostics: [...t.diagnostics, ...typeDiags],
        support: typeDiags.isEmpty ? t.support : SupportStatus.partial,
      ),
    );
  }
  return ApiModule(
    platform: module.platform,
    sdkVersion: module.sdkVersion,
    sourceRevision: module.sourceRevision,
    generatorVersion: module.generatorVersion,
    types: types,
    diagnostics: module.diagnostics,
  );
}
