import 'package:native_api_ir/native_api_ir.dart';

/// Objective-C classes, protocols and structs that `package:objective_c`
/// already provides (generated by the Dart team's ffigen from Foundation).
/// Generated code references them (`objc.NSString`) instead of redefining
/// them, like the Android target uses `JString`/`JObject` from package:jni.
const objectiveCRuntimeTypes = {
  'NSArray', 'NSAttributedString', 'NSBundle', 'NSCharacterSet', 'NSCoder',
  'NSData', 'NSDate', 'NSDictionary', 'NSEnumerator', 'NSError', 'NSIndexSet',
  'NSInputStream', 'NSInvocation', 'NSItemProvider', 'NSLocale',
  'NSMethodSignature', 'NSMutableArray', 'NSMutableData',
  'NSMutableDictionary', 'NSMutableIndexSet', 'NSMutableOrderedSet',
  'NSMutableSet', 'NSMutableString', 'NSNotification', 'NSNull', 'NSNumber',
  'NSObject', 'NSOrderedCollectionChange', 'NSOrderedCollectionDifference',
  'NSOrderedSet', 'NSOutputStream', 'NSPort', 'NSPortMessage', 'NSProgress',
  'NSRunLoop', 'NSSet', 'NSStream', 'NSString', 'NSTimer', 'NSURL',
  'NSURLHandle', 'NSValue', 'Protocol',
  // Protocols.
  'NSCoding', 'NSCopying', 'NSFastEnumeration', 'NSItemProviderReading',
  'NSItemProviderWriting', 'NSMutableCopying', 'NSObjectProtocol',
  'NSPortDelegate', 'NSSecureCoding', 'NSStreamDelegate',
  // Structs.
  'NSRange', 'NSFastEnumerationState', 'NSEdgeInsets',
};

/// Whether [id] (e.g. `Foundation.NSString`) is provided by package:objective_c.
bool isRuntimeProvided(String id) {
  final i = id.indexOf('.');
  if (i < 0) return false;
  final module = id.substring(0, i);
  return (module == 'Foundation' || module == 'ObjectiveC') &&
      objectiveCRuntimeTypes.contains(id.substring(i + 1));
}

/// Whether [t] is a Cocoa `NSError **` out-parameter (mapped to a thrown
/// `NativeObjCError` instead of a raw pointer).
bool isErrorOutParameter(TypeRef t) =>
    t is PointerTypeRef &&
    t.pointee is DeclaredTypeRef &&
    (t.pointee as DeclaredTypeRef).name == 'Foundation.NSError';

/// How a block parameter is created from a Dart function.
enum BlockMode {
  /// A closure block for `NS_NOESCAPE` parameters: invoked synchronously
  /// while Dart is inside the call (an FFI callback is only valid then; a
  /// block called later from the run loop would need native code to enter
  /// the isolate). Any argument and result types.
  sync,

  /// A `NativeCallable.listener` block: callable from any thread, delivered
  /// asynchronously. Only `void` blocks whose arguments are all primitives
  /// (objects could be freed before Dart reads them).
  listener,
}

bool _blockValueSupported(TypeRef t, Map<String, ApiType> types) => switch (t) {
  PrimitiveTypeRef() => true,
  DeclaredTypeRef(:final name) =>
    name != 'objc.unsupported' &&
        name != 'objc.Class' &&
        name != 'objc.SEL' &&
        types[name]?.kind != TypeKind.struct,
  PointerTypeRef(:final pointee) => pointee is PrimitiveTypeRef,
  _ => false,
};

bool _blockPrimitive(TypeRef t, Map<String, ApiType> types) => switch (t) {
  PrimitiveTypeRef() => true,
  DeclaredTypeRef(:final name) => types[name]?.kind == TypeKind.enumType,
  _ => false,
};

/// The creation mode for block parameter [p] of [m], or null when the
/// block cannot be created from Dart without a native trampoline.
BlockMode? blockMode(ApiMethod m, ApiParameter p, Map<String, ApiType> types) {
  final b = p.type;
  if (b is! BlockTypeRef) return null;
  final values = [b.returnType, ...b.parameters];
  if (!values.every((t) => _blockValueSupported(t, types))) return null;
  final noescape = p.annotations.any((a) => a.type == 'objc.noescape');
  if (noescape) return BlockMode.sync;
  final isVoid =
      b.returnType is PrimitiveTypeRef &&
      (b.returnType as PrimitiveTypeRef).kind == PrimitiveKind.void_;
  if (isVoid && b.parameters.every((t) => _blockPrimitive(t, types))) {
    return BlockMode.listener;
  }
  return null;
}

/// Target-capability analysis for Dart over `package:objective_c`.
ApiModule planDartObjC(ApiModule module) {
  final byId = {for (final t in module.types) t.id: t};
  final generated = {
    for (final t in module.types)
      if (t.isGeneratable) t.id,
  };

  // Value types (structs) that cannot be laid out, e.g. bit-field structs:
  // passing them by value is impossible without a native shim.
  final opaqueStructs = {
    for (final t in module.types)
      if (t.kind == TypeKind.struct && !t.isGeneratable) t.id,
  };

  Diagnostic d(
    DiagnosticCode c,
    String id,
    String msg, [
    Severity s = Severity.warning,
  ]) => Diagnostic(c, msg, symbolId: id, severity: s);

  // Returns an unsupported reason for a type used in a signature, or null.
  String? unsupportedReason(TypeRef t) => switch (t) {
    BlockTypeRef() => 'E004',
    ArrayTypeRef() => 'E002',
    DeclaredTypeRef(:final name)
        when name == 'objc.unsupported' ||
            name == 'objc.Class' ||
            name == 'objc.SEL' =>
      'E002',
    DeclaredTypeRef(:final name) when opaqueStructs.contains(name) => 'E002',
    PointerTypeRef(:final pointee) => switch (pointee) {
      BlockTypeRef() => 'E004',
      _ => null,
    },
    _ => null,
  };

  final types = <ApiType>[];
  for (final t in module.types) {
    if (!t.isGeneratable) {
      types.add(t);
      continue;
    }
    final methods = <ApiMethod>[];
    for (final m in t.methods) {
      if (!m.isGeneratable) {
        methods.add(m);
        continue;
      }
      final extra = <Diagnostic>[];
      Diagnostic? blocked;
      for (final p in m.parameters) {
        if (p.type is! BlockTypeRef) continue;
        if (blockMode(m, p, byId) == null) {
          blocked ??= d(
            DiagnosticCode.unsupportedCallback,
            m.id,
            'Block parameter `${p.name}` (${p.type.display}) is escaping and takes objects or returns a value: it may be invoked later or off the isolate thread, which needs a native trampoline',
          );
        }
      }
      for (final ty in [
        m.returnType,
        for (final p in m.parameters)
          if (p.type is! BlockTypeRef) p.type,
      ]) {
        final r = unsupportedReason(ty);
        if (r == 'E004') {
          blocked ??= d(
            DiagnosticCode.unsupportedCallback,
            m.id,
            'Objective-C blocks are not supported by the Flutter iOS target yet (needs native trampolines)',
          );
        } else if (r == 'E002') {
          blocked ??= d(
            DiagnosticCode.unsupportedType,
            m.id,
            'Unsupported type ${ty.display}',
          );
        }
        if (ty is PointerTypeRef && !isErrorOutParameter(ty)) {
          extra.add(
            d(
              DiagnosticCode.unsupportedType,
              m.id,
              'Raw C pointer ${ty.display}: exposed as ffi.Pointer (unsafe)',
              Severity.info,
            ),
          );
        }
        for (final n in ty.referencedTypes) {
          if (!n.startsWith('objc.') &&
              !generated.contains(n) &&
              !isRuntimeProvided(n)) {
            extra.add(
              d(
                DiagnosticCode.outsideClosure,
                m.id,
                'Outside the generation closure, exposed as ObjCObject: $n',
                Severity.info,
              ),
            );
          }
        }
      }
      final support = blocked != null
          ? SupportStatus.unsupported
          : extra.isEmpty
          ? m.support
          : SupportStatus.partial;
      methods.add(
        ApiMethod(
          id: m.id,
          name: m.name,
          kind: m.kind,
          returnType: m.returnType,
          parameters: m.parameters,
          typeParameters: m.typeParameters,
          throws: m.throws,
          threading: m.threading,
          permissions: m.permissions,
          asyncKind: m.asyncKind,
          nativeDescriptor: m.nativeDescriptor,
          modifiers: m.modifiers,
          annotations: m.annotations,
          availability: m.availability,
          visibility: m.visibility,
          support: support,
          documentation: m.documentation,
          diagnostics: [...m.diagnostics, ?blocked, ...extra.toSet()],
        ),
      );
    }
    final typeDiags = <Diagnostic>[
      if (t.kind == TypeKind.protocol)
        d(
          DiagnosticCode.unsupportedCallback,
          t.id,
          'Implementing Objective-C protocols in Dart is not supported by the Flutter iOS target yet; the protocol is usable for typing and calling',
          Severity.info,
        ),
      if (isRuntimeProvided(t.id))
        d(
          DiagnosticCode.outsideClosure,
          t.id,
          'Provided by package:objective_c (referenced, not regenerated)',
          Severity.info,
        ),
    ];
    types.add(
      t.copyWith(
        methods: methods,
        diagnostics: [...t.diagnostics, ...typeDiags],
        support: typeDiags.isEmpty ? t.support : SupportStatus.partial,
      ),
    );
  }
  return ApiModule(
    platform: module.platform,
    sdkVersion: module.sdkVersion,
    sourceRevision: module.sourceRevision,
    generatorVersion: module.generatorVersion,
    types: types,
    diagnostics: module.diagnostics,
  );
}
