# GENERATED CODE - DO NOT MODIFY BY HAND.
# Generated by native-api-bindgen 0.1.0-dev.1 (IR schema 2, runtime 0.1.0-dev.1)
# Source SDK: Apple SDK fixture
# Derived from SDK metadata installed on the build machine; see
# docs/legal/source-provenance.md before redistributing.

# CocoaPods spec for the iOS half of the generated bindings library. Add to
# ios/Podfile:   pod 'NativeApiBindings', :path => '../<library dir>'
# and register the Turbo Module provider in package.json codegenConfig:
#   "ios": {"modulesProvider": {"NativeApiBindgen": "NabModuleProvider"}}
Pod::Spec.new do |s|
  s.name = 'NativeApiBindings'
  s.version = '0.1.0.1'
  s.summary = 'native-api-bindgen bindings generated from the local iOS SDK (local-only).'
  s.homepage = 'https://example.invalid/native-api-bindings'
  s.license = {:type => 'Apache-2.0'}
  s.authors = 'native-api-bindgen'
  s.platforms = {:ios => '15.0'}
  s.source = {:path => '.'}
  s.source_files = [
    'cpp/runtime/NativeApiBindgen.{h,cpp}',
    'cpp/runtime-objc/*.{h,mm}',
    'cpp/generated/NabBindingsObjC.cpp',
    'cpp/generated/NabBlocksObjC.mm',
  ]
  s.frameworks = []
  s.pod_target_xcconfig = {
    'CLANG_CXX_LANGUAGE_STANDARD' => 'c++20',
    'CLANG_ENABLE_OBJC_ARC' => 'YES',
  }
  install_modules_dependencies(s)
end
