# GENERATED CODE - DO NOT MODIFY BY HAND.
# Generated by native-api-bindgen 0.1.0-beta.1 (IR schema 2, runtime 0.1.0-beta.1)
# Source SDK: fixture (synthetic test classes)
# Derived from SDK metadata installed on the build machine; see
# docs/legal/source-provenance.md before redistributing.

# Include from android/app/src/main/jni/CMakeLists.txt after the React Native
# application include:  include(<path>/native-api-bindings/native-api-bindings.cmake)
set(NAB_DIR ${CMAKE_CURRENT_LIST_DIR})
target_sources(${CMAKE_PROJECT_NAME} PRIVATE
    ${NAB_DIR}/cpp/runtime/NabRuntime.cpp
    ${NAB_DIR}/cpp/runtime/NativeApiBindgen.cpp
    ${NAB_DIR}/cpp/generated/NabBindings.cpp)
target_include_directories(${CMAKE_PROJECT_NAME} PUBLIC ${NAB_DIR}/cpp/runtime)
