import 'dart:convert';

import 'package:native_api_core/native_api_core.dart';
import 'package:native_api_ir/native_api_ir.dart';

/// Static per-symbol API documentation for generated bindings (TRD §98):
/// native symbol, generated symbol, availability, threading, permissions,
/// support status with reason codes, provenance and a link to the official
/// reference. Metadata only: no SDK documentation text is copied
/// (`documentationMode: links-only`).
final class DocsSite {
  /// Creates a site over generation [states] (`label` such as `android`).
  DocsSite(this.states);

  /// Generation states.
  final List<
    ({String label, ApiModule module, List<Map<String, Object?>> bindings})
  >
  states;

  static const _css = '''
body{font:15px/1.5 -apple-system,system-ui,Segoe UI,Roboto,sans-serif;margin:0 auto;max-width:1100px;padding:16px;color:#1d1d1f;background:#fff}
@media (prefers-color-scheme:dark){body{color:#e8e8ea;background:#141416}a{color:#7fb3ff}table td,table th{border-color:#333}}
h1{font-size:1.5rem}h2{font-size:1.15rem;margin-top:2rem}code{font:13px ui-monospace,Menlo,monospace}
table{border-collapse:collapse;width:100%;margin:8px 0}td,th{border:1px solid #ddd;padding:4px 8px;text-align:left;vertical-align:top}
.ok{color:#1b7f3b}.partial{color:#a56300}.no{color:#b3261e}.muted{opacity:.7}nav{margin-bottom:12px}
''';

  /// Writes the site into [guard]'s root; returns the number of pages.
  int write(OutputGuard guard) {
    var pages = 0;
    final index = StringBuffer();
    index.writeln('<h1>Generated API reference</h1>');
    index.writeln(
      '<p class="muted">Generated by ${_e(ProjectInfo.name)} ${_e(ProjectInfo.generatorVersion)} from the generation state of this project. Metadata only; follow the reference links for official documentation.</p>',
    );
    for (final s in states) {
      final byType = <String, List<Map<String, Object?>>>{};
      for (final b in s.bindings) {
        final id = b['symbolId'] as String? ?? '';
        final owner = id.contains('#') ? id.substring(0, id.indexOf('#')) : id;
        (byType[owner] ??= []).add(b);
      }
      final types = s.module.types.toList()
        ..sort((a, b) => a.id.compareTo(b.id));
      final generated = types.where((t) => t.isGeneratable).length;
      index.writeln(
        '<h2>${_e(s.label)} — ${_e(s.module.platform.name)} SDK ${_e(s.module.sdkVersion)}</h2>',
      );
      index.writeln(
        '<p>${types.length} types in the closure, $generated generated.</p><ul>',
      );
      for (final t in types) {
        final page = _pagePath(s.label, t.id);
        index.writeln(
          '<li><a href="$page"><code>${_e(t.id)}</code></a> ${_status(t)}</li>',
        );
        guard.writeString(
          page,
          _page(
            '${t.name} — ${s.label}',
            _typePage(s.label, t, byType[t.id] ?? const [], depth: 2),
            depth: 2,
          ),
        );
        pages++;
      }
      index.writeln('</ul>');
    }
    guard.writeString('index.html', _page('API reference', index.toString()));
    return pages + 1;
  }

  static String _pagePath(String label, String id) {
    final safe = id.replaceAll(RegExp(r'[^A-Za-z0-9_.$-]'), '_');
    return '${label.replaceAll('/', '_')}/$safe.html';
  }

  static String _status(ApiNode n) => switch (n.support) {
    SupportStatus.supported => '<span class="ok">generated</span>',
    SupportStatus.partial => '<span class="partial">partial</span>',
    _ => '<span class="no">not generated</span>',
  };

  static String _availability(Availability a) {
    final parts = <String>[
      if (a.introduced != null) 'since ${a.introduced}',
      if (a.deprecated != null) 'deprecated ${a.deprecated}',
      if (a.removed != null) 'removed ${a.removed}',
      for (final e in a.platforms.entries)
        '${e.key}: ${e.value.unavailable ? 'unavailable' : '${e.value.introduced ?? '?'}+'}',
    ];
    return parts.isEmpty ? '—' : _e(parts.join(', '));
  }

  static String _diags(List<Diagnostic> ds) => ds.isEmpty
      ? ''
      : '<br>${ds.map((d) => '<span class="muted">${_e(d.code.code)} ${_e(d.code.label)}: ${_e(d.message)}</span>').join('<br>')}';

  String _typePage(
    String label,
    ApiType t,
    List<Map<String, Object?>> bindings, {
    required int depth,
  }) {
    final generatedAs = {
      for (final b in bindings)
        b['symbolId'] as String: '${b['generated']} (${b['file']})',
    };
    final b = StringBuffer()
      ..writeln(
        '<nav><a href="${'../' * (depth - 1)}index.html">Index</a></nav>',
      )
      ..writeln('<h1><code>${_e(t.id)}</code></h1>')
      ..writeln('<table>')
      ..writeln('<tr><th>Kind</th><td>${_e(t.kind.name)}</td></tr>')
      ..writeln(
        '<tr><th>Status</th><td>${_status(t)}${_diags(t.diagnostics)}</td></tr>',
      )
      ..writeln(
        '<tr><th>Generated as</th><td><code>${_e(generatedAs[t.id] ?? '—')}</code></td></tr>',
      )
      ..writeln(
        '<tr><th>Availability</th><td>${_availability(t.availability)}</td></tr>',
      )
      ..writeln(
        '<tr><th>Threading</th><td>${_e(t.threading == Threading.unspecified ? '—' : t.threading.name)}</td></tr>',
      )
      ..writeln(
        '<tr><th>Provenance</th><td>${_e('${t.provenance.sourceKind}, ${t.provenance.localArtifact ?? ''} ${t.provenance.artifactEntry ?? ''}'.trim())}</td></tr>',
      );
    final ref = t.documentation.reference;
    if (ref != null) {
      b.writeln(
        '<tr><th>Reference</th><td><a href="${_e(ref)}" rel="noopener">${_e(ref)}</a></td></tr>',
      );
    }
    b.writeln('</table>');
    final members = <ApiNode>[...t.fields, ...t.methods]
      ..sort((x, y) => x.id.compareTo(y.id));
    if (members.isNotEmpty) {
      b
        ..writeln('<h2>Members (${members.length})</h2>')
        ..writeln(
          '<table><tr><th>Native symbol</th><th>Generated as</th><th>Availability</th><th>Threading / permissions</th><th>Status</th></tr>',
        );
      for (final m in members) {
        final thread = m is ApiMethod
            ? [
                if (m.threading != Threading.unspecified) m.threading.name,
                ...m.permissions,
              ].join(', ')
            : '';
        final mref = m.documentation.reference;
        b.writeln(
          '<tr><td><code>${_e(m.id.substring(m.id.indexOf('#') + 1))}</code>${mref == null ? '' : ' <a href="${_e(mref)}" rel="noopener">ref</a>'}</td>'
          '<td><code>${_e(generatedAs[m.id] ?? '—')}</code></td>'
          '<td>${_availability(m.availability)}</td>'
          '<td>${_e(thread.isEmpty ? '—' : thread)}</td>'
          '<td>${_status(m)}${_diags(m.diagnostics)}</td></tr>',
        );
      }
      b.writeln('</table>');
    }
    return b.toString();
  }

  static String _page(String title, String body, {int depth = 1}) =>
      '<!doctype html>\n<html lang="en"><head><meta charset="utf-8">'
      '<meta name="viewport" content="width=device-width,initial-scale=1">'
      '<title>${_e(title)}</title><style>$_css</style></head><body>\n$body\n</body></html>\n';

  static String _e(String s) => const HtmlEscape().convert(s);
}
