// Embeds runtimes/jsi and runtimes/jni sources into
// lib/src/runtime_sources.g.dart so the CLI can write them into apps
// regardless of how it is installed. Run after editing the runtime:
//   dart run packages/native_api_react_native_android/tool/embed_runtime.dart
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

/// Runtime files: output path in the generated library -> repo path.
const files = {
  'cpp/runtime/NabRuntime.h': 'runtimes/jsi/cpp/NabRuntime.h',
  'cpp/runtime/NabRuntime.cpp': 'runtimes/jsi/cpp/NabRuntime.cpp',
  'cpp/runtime/NativeApiBindgen.h': 'runtimes/jsi/cpp/NativeApiBindgen.h',
  'cpp/runtime/NativeApiBindgen.cpp': 'runtimes/jsi/cpp/NativeApiBindgen.cpp',
  'src/runtime.ts': 'runtimes/jsi/ts/runtime.ts',
  'specs/NativeApiBindgen.ts': 'runtimes/jsi/ts/specs/NativeApiBindgen.ts',
  'android/java/dev/nativeapibindgen/runtime/NabInvocationHandler.java':
      'runtimes/jni/java/dev/nativeapibindgen/runtime/NabInvocationHandler.java',
  'android/java/dev/nativeapibindgen/runtime/NabContext.java':
      'runtimes/jni/java/dev/nativeapibindgen/runtime/NabContext.java',
  'android/java/dev/nativeapibindgen/runtime/NabContinuation.java':
      'runtimes/jni/java/dev/nativeapibindgen/runtime/NabContinuation.java',
  'android/java/dev/nativeapibindgen/runtime/NabViews.java':
      'runtimes/jni/java/dev/nativeapibindgen/runtime/NabViews.java',
  'android/java/dev/nativeapibindgen/runtime/NabNativeViewManager.java':
      'runtimes/jni/java/dev/nativeapibindgen/runtime/NabNativeViewManager.java',
  'android/java/dev/nativeapibindgen/runtime/NabUiPackage.java':
      'runtimes/jni/java/dev/nativeapibindgen/runtime/NabUiPackage.java',
  'src/native-view.ts': 'runtimes/jsi/ts/native-view.ts',
};

String render(String root) {
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/embed_runtime.dart. Do not edit.')
    ..writeln(
      '// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars',
    )
    ..writeln()
    ..writeln(
      '/// Runtime sources keyed by output path inside the bindings library.',
    )
    ..writeln('const runtimeSources = <String, String>{');
  for (final e in files.entries) {
    final text = File(p.join(root, e.value)).readAsStringSync();
    b.writeln(
      '  ${jsonEncode(e.key)}: ${jsonEncode(text).replaceAll(r'$', r'\$')},',
    );
  }
  b.writeln('};');
  return b.toString();
}

void main() {
  var dir = Directory.current;
  while (!File(
    p.join(dir.path, 'runtimes', 'jsi', 'cpp', 'NabRuntime.h'),
  ).existsSync()) {
    dir = dir.parent;
  }
  final out = p.join(
    dir.path,
    'packages',
    'native_api_react_native_android',
    'lib',
    'src',
    'runtime_sources.g.dart',
  );
  File(out).writeAsStringSync(render(dir.path));
  // Keep the file as `dart format` (checked by CI) leaves it.
  Process.runSync('dart', ['format', out]);
}
