import 'dart:async';

import 'package:flutter/material.dart';

import 'src/showcase.dart';

void main() => runApp(const ShowcaseApp());

/// Android tasks done entirely through bindings generated by
/// native-api-bindgen: no MethodChannel, no plugin per API.
class ShowcaseApp extends StatelessWidget {
  /// Creates the app.
  const ShowcaseApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
    title: 'native-api-bindgen · Android',
    theme: ThemeData(colorSchemeSeed: Colors.teal, useMaterial3: true),
    darkTheme: ThemeData(
      colorSchemeSeed: Colors.teal,
      brightness: Brightness.dark,
      useMaterial3: true,
    ),
    home: const ShowcasePage(),
  );
}

/// Live device dashboard plus one card per task.
class ShowcasePage extends StatefulWidget {
  /// Creates the page.
  const ShowcasePage({super.key});

  @override
  State<ShowcasePage> createState() => _ShowcasePageState();
}

class _ShowcasePageState extends State<ShowcasePage> {
  final _text = TextEditingController(
    text: 'Hello from Dart, through generated Android bindings.',
  );
  DeviceStatus? _status;
  String? _note;
  Timer? _timer;

  @override
  void initState() {
    super.initState();
    _refresh();
    _note = Showcase.loadNote();
    _timer = Timer.periodic(const Duration(seconds: 3), (_) => _refresh());
  }

  @override
  void dispose() {
    _timer?.cancel();
    _text.dispose();
    super.dispose();
  }

  void _refresh() => setState(() => _status = Showcase.deviceStatus());

  Future<void> _run(String label, FutureOr<String?> Function() task) async {
    final messenger = ScaffoldMessenger.of(context);
    try {
      final result = await task();
      messenger.showSnackBar(SnackBar(content: Text(result ?? '$label: done')));
    } on Object catch (e) {
      messenger.showSnackBar(SnackBar(content: Text('$label failed: $e')));
    }
  }

  @override
  Widget build(BuildContext context) {
    final s = _status;
    return Scaffold(
      appBar: AppBar(title: const Text('Native Android APIs from Dart')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          if (s != null) DeviceDashboard(status: s),
          const SizedBox(height: 16),
          TextField(
            controller: _text,
            minLines: 1,
            maxLines: 3,
            decoration: const InputDecoration(
              labelText: 'Text used by the tasks below',
              border: OutlineInputBorder(),
            ),
          ),
          const SizedBox(height: 16),
          _Task(
            icon: Icons.record_voice_over,
            title: 'Speak',
            api: 'TextToSpeech + OnInitListener implemented in Dart',
            onPressed: () => _run('Speak', () async {
              await Speaker.instance.speak(_text.text);
              return 'Speaking…';
            }),
          ),
          _Task(
            icon: Icons.share,
            title: 'Share',
            api: 'Intent.ACTION_SEND + Intent.createChooser',
            onPressed: () => _run('Share', () {
              Showcase.share(_text.text);
              return 'Chooser opened';
            }),
          ),
          _Task(
            icon: Icons.copy,
            title: 'Copy, then paste back',
            api: 'ClipboardManager + ClipData',
            onPressed: () => _run('Clipboard', () {
              Showcase.copy(_text.text);
              return 'Clipboard now holds: ${Showcase.paste()}';
            }),
          ),
          _Task(
            icon: Icons.save,
            title: 'Save as note',
            api: 'SharedPreferences.Editor (survives restarts)',
            subtitle: _note == null ? 'No note saved yet' : 'Saved: $_note',
            onPressed: () => _run('Save', () {
              Showcase.saveNote(_text.text);
              setState(() => _note = Showcase.loadNote());
              return 'Note saved';
            }),
          ),
          _Task(
            icon: Icons.vibration,
            title: 'Vibrate',
            api: 'Vibrator + VibrationEffect (API 26+, runtime-guarded)',
            onPressed: () => _run('Vibrate', Showcase.vibrate),
          ),
          _Task(
            icon: Icons.chat_bubble_outline,
            title: 'Native toast',
            api: 'Toast.makeText',
            onPressed: () => _run('Toast', () {
              Showcase.toast(_text.text);
              return null;
            }),
          ),
          _Task(
            icon: Icons.location_on,
            title: 'Location settings',
            api: 'Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS)',
            onPressed: () => _run('Location settings', () {
              Showcase.openLocationSettings();
              return 'Location settings opened';
            }),
          ),
          _Task(
            icon: Icons.admin_panel_settings,
            title: 'App permissions (location)',
            api: 'Settings.ACTION_APPLICATION_DETAILS_SETTINGS + package: URI',
            onPressed: () => _run('App permissions', () {
              Showcase.openAppPermissions();
              return 'App settings opened';
            }),
          ),
          _Task(
            icon: Icons.open_in_browser,
            title: 'Open Android reference',
            api: 'Intent.ACTION_VIEW + Activity.startActivity',
            onPressed: () => _run('Open', () {
              Showcase.openUrl('https://developer.android.com/reference');
              return 'Browser opened';
            }),
          ),
        ],
      ),
    );
  }
}

/// Battery, memory, storage and network from a [DeviceStatus] snapshot.
class DeviceDashboard extends StatelessWidget {
  /// Creates the dashboard for [status].
  const DeviceDashboard({super.key, required this.status});

  /// The snapshot to show.
  final DeviceStatus status;

  static String _gb(int bytes) =>
      '${(bytes / (1 << 30)).toStringAsFixed(1)} GB';

  @override
  Widget build(BuildContext context) {
    final s = status;
    final theme = Theme.of(context);
    final usedMem = s.totalMemBytes - s.availMemBytes;
    final usedDisk = s.totalStorageBytes - s.freeStorageBytes;
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(s.device, style: theme.textTheme.titleLarge),
            Text(
              'Android API ${s.apiLevel ?? '?'} · refreshes every 3 s',
              style: theme.textTheme.bodySmall,
            ),
            const SizedBox(height: 16),
            _Meter(
              icon: s.charging
                  ? Icons.battery_charging_full
                  : Icons.battery_std,
              label: 'Battery',
              value: s.batteryPercent == null ? null : s.batteryPercent! / 100,
              detail: s.batteryPercent == null
                  ? 'unknown'
                  : '${s.batteryPercent}%${s.charging ? ' · charging' : ''}',
            ),
            _Meter(
              icon: Icons.memory,
              label: 'Memory',
              value: usedMem / s.totalMemBytes,
              detail:
                  '${_gb(usedMem)} of ${_gb(s.totalMemBytes)} used'
                  '${s.lowMemory ? ' · LOW' : ''}',
            ),
            _Meter(
              icon: Icons.sd_storage,
              label: 'Storage',
              value: usedDisk / s.totalStorageBytes,
              detail:
                  '${_gb(s.freeStorageBytes)} free of ${_gb(s.totalStorageBytes)}',
            ),
            ListTile(
              contentPadding: EdgeInsets.zero,
              leading: const Icon(Icons.network_check),
              title: const Text('Network'),
              subtitle: Text(s.network),
            ),
          ],
        ),
      ),
    );
  }
}

class _Meter extends StatelessWidget {
  const _Meter({
    required this.icon,
    required this.label,
    required this.value,
    required this.detail,
  });

  final IconData icon;
  final String label;
  final double? value;
  final String detail;

  @override
  Widget build(BuildContext context) => Padding(
    padding: const EdgeInsets.symmetric(vertical: 6),
    child: Row(
      children: [
        Icon(icon),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Text(label),
                  const Spacer(),
                  Text(detail, style: Theme.of(context).textTheme.bodySmall),
                ],
              ),
              const SizedBox(height: 4),
              LinearProgressIndicator(value: value, minHeight: 6),
            ],
          ),
        ),
      ],
    ),
  );
}

class _Task extends StatelessWidget {
  const _Task({
    required this.icon,
    required this.title,
    required this.api,
    required this.onPressed,
    this.subtitle,
  });

  final IconData icon;
  final String title;
  final String api;
  final String? subtitle;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) => Card(
    child: ListTile(
      leading: Icon(icon),
      title: Text(title),
      subtitle: Text(subtitle == null ? api : '$api\n$subtitle'),
      isThreeLine: subtitle != null,
      trailing: const Icon(Icons.play_arrow),
      onTap: onPressed,
    ),
  );
}
