// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-dev.1 (IR schema 2, runtime 0.1.0-dev.1)
// Source SDK: Apple SDK fixture
// Derived from SDK metadata installed on the build machine; see
// docs/legal/source-provenance.md before redistributing.

// ignore_for_file: camel_case_types, comment_references, constant_identifier_names, deprecated_member_use_from_same_package, invalid_use_of_internal_member, library_prefixes, non_constant_identifier_names, no_leading_underscores_for_local_identifiers, public_member_api_docs, unused_element, unused_import, unused_field, lines_longer_than_80_chars, sort_constructors_first

/// Objective-C block factories shared by the generated libraries: one
/// per distinct native block signature and creation mode (names are
/// signature hashes).
library;

import 'dart:ffi' as ffi;

import 'package:objective_c/objective_c.dart' as objc;

/// Listener block `void (^)(boolean, long)`: callable from any thread; [fn] runs
/// asynchronously on the creating isolate. With [once] (completion
/// handlers) the callable is closed after the first call.
objc.ObjCBlockBase listener_1jxrv3498gv8s(void Function(bool, int) fn, {bool once = false}) {
  late final ffi.NativeCallable<ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Bool, ffi.Int64)> cb;
  cb = ffi.NativeCallable<ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Bool, ffi.Int64)>.listener((ffi.Pointer<objc.ObjCBlockImpl> block, bool a0, int a1) {
    if (once) cb.close();
    fn(a0, a1);
  });
  if (!once) cb.keepIsolateAlive = false;
  return objc.ObjCBlockBase(
    objc.newPointerBlock(cb.nativeFunction.cast(), ffi.nullptr),
    retain: false,
    release: true,
  );
}

/// Listener block `void (^)(boolean)`: callable from any thread; [fn] runs
/// asynchronously on the creating isolate. With [once] (completion
/// handlers) the callable is closed after the first call.
objc.ObjCBlockBase listener_olxutvjws7l6(void Function(bool) fn, {bool once = false}) {
  late final ffi.NativeCallable<ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Bool)> cb;
  cb = ffi.NativeCallable<ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Bool)>.listener((ffi.Pointer<objc.ObjCBlockImpl> block, bool a0) {
    if (once) cb.close();
    fn(a0);
  });
  if (!once) cb.keepIsolateAlive = false;
  return objc.ObjCBlockBase(
    objc.newPointerBlock(cb.nativeFunction.cast(), ffi.nullptr),
    retain: false,
    release: true,
  );
}

/// Listener block `void (^)()`: callable from any thread; [fn] runs
/// asynchronously on the creating isolate. With [once] (completion
/// handlers) the callable is closed after the first call.
objc.ObjCBlockBase listener_s185jcjjbqd(void Function() fn, {bool once = false}) {
  late final ffi.NativeCallable<ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>)> cb;
  cb = ffi.NativeCallable<ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>)>.listener((ffi.Pointer<objc.ObjCBlockImpl> block) {
    if (once) cb.close();
    fn();
  });
  if (!once) cb.keepIsolateAlive = false;
  return objc.ObjCBlockBase(
    objc.newPointerBlock(cb.nativeFunction.cast(), ffi.nullptr),
    retain: false,
    release: true,
  );
}

int _sync_1g5gri0bovfu1(ffi.Pointer<objc.ObjCBlockImpl> block, int a0, int a1) =>
    (objc.getBlockClosure(block) as int Function(int, int))(a0, a1);
final _sync_1g5gri0bovfu1_callable = ffi.Pointer.fromFunction<ffi.Int64 Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Int64, ffi.Int64)>(_sync_1g5gri0bovfu1, 0).cast<ffi.Void>();

/// Synchronous block `long (^)(long, long)`: must be invoked on the creating isolate's thread.
objc.ObjCBlockBase sync_1g5gri0bovfu1(int Function(int, int) fn) => objc.ObjCBlockBase(
  objc.newClosureBlock(_sync_1g5gri0bovfu1_callable, fn, true),
  retain: false,
  release: true,
);

ffi.Pointer<objc.ObjCObjectImpl> _sync_mqz3yl480vdr(ffi.Pointer<objc.ObjCBlockImpl> block, ffi.Pointer<objc.ObjCObjectImpl> a0) =>
    (objc.getBlockClosure(block) as ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<objc.ObjCObjectImpl>))(a0);
final _sync_mqz3yl480vdr_callable = ffi.Pointer.fromFunction<ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Pointer<objc.ObjCObjectImpl>)>(_sync_mqz3yl480vdr).cast<ffi.Void>();

/// Synchronous block `Foundation.NSString (^)(Foundation.NSString)`: must be invoked on the creating isolate's thread.
objc.ObjCBlockBase sync_mqz3yl480vdr(ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<objc.ObjCObjectImpl>) fn) => objc.ObjCBlockBase(
  objc.newClosureBlock(_sync_mqz3yl480vdr_callable, fn, true),
  retain: false,
  release: true,
);

void _sync_wyw89bm4fawo(ffi.Pointer<objc.ObjCBlockImpl> block, int a0, ffi.Pointer<ffi.Bool> a1) =>
    (objc.getBlockClosure(block) as void Function(int, ffi.Pointer<ffi.Bool>))(a0, a1);
final _sync_wyw89bm4fawo_callable = ffi.Pointer.fromFunction<ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Uint64, ffi.Pointer<ffi.Bool>)>(_sync_wyw89bm4fawo).cast<ffi.Void>();

/// Synchronous block `void (^)(uint64, boolean *)`: must be invoked on the creating isolate's thread.
objc.ObjCBlockBase sync_wyw89bm4fawo(void Function(int, ffi.Pointer<ffi.Bool>) fn) => objc.ObjCBlockBase(
  objc.newClosureBlock(_sync_wyw89bm4fawo_callable, fn, true),
  retain: false,
  release: true,
);

