// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-dev.1 (IR schema 2, runtime 0.1.0-dev.1)
// Source SDK: Apple SDK fixture
// Derived from SDK metadata installed on the build machine; see
// docs/legal/source-provenance.md before redistributing.

/// Runtime helpers for the generated Apple bindings.
library;

import 'dart:ffi' as ffi;

import 'package:ffi/ffi.dart' as pffi;
import 'package:objective_c/objective_c.dart' as objc;

/// An Objective-C `NSError` reported through an `NSError **` out-parameter.
final class NativeObjCError implements Exception {
  /// Creates an error.
  const NativeObjCError(this.domain, this.code, this.description);

  /// Copies the fields of [error].
  factory NativeObjCError.fromNSError(objc.NSError error) => NativeObjCError(
    error.domain.toDartString(),
    error.code,
    error.localizedDescription.toDartString(),
  );

  /// `NSError.domain`.
  final String domain;

  /// `NSError.code`.
  final int code;

  /// `NSError.localizedDescription`.
  final String description;

  @override
  String toString() => 'NativeObjCError($domain, $code): $description';
}

final _pthreadMainNp = ffi.DynamicLibrary.process()
    .lookupFunction<ffi.Int Function(), int Function()>('pthread_main_np');

/// Whether the caller runs on the process's main thread.
bool isMainThread() => _pthreadMainNp() != 0;

/// A main-actor API (`NS_SWIFT_UI_ACTOR`) was called off the main thread
/// (E013 THREADING_CONSTRAINT). Raised by debug-build checks only.
final class NativeThreadingError extends Error {
  /// Creates the error.
  NativeThreadingError(this.symbol);

  /// The Objective-C member, e.g. `-[UIView setAlpha:]`.
  final String symbol;

  @override
  String toString() =>
      'E013 THREADING_CONSTRAINT: $symbol is main-actor isolated and must be '
      'called on the main thread (the root isolate on iOS)';
}

/// Used as `assert(checkMainThread(...))` before main-actor calls.
bool checkMainThread(String symbol) {
  if (isMainThread()) return true;
  throw NativeThreadingError(symbol);
}

/// Allocates a zeroed `NSError *` slot for an out-parameter.
ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> errorSlot() =>
    pffi.calloc<ffi.Pointer<objc.ObjCObjectImpl>>();

/// Throws [NativeObjCError] when the call [failed] and set the slot.
/// Cocoa only defines the out-parameter when the return value reports
/// failure (`NO` or `nil`), so the slot is ignored otherwise.
void throwIfError(
  ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> slot, {
  required bool failed,
}) {
  if (!failed || slot.value.address == 0) return;
  throw NativeObjCError.fromNSError(
    objc.NSError.fromPointer(slot.value, retain: true, release: true),
  );
}

/// Frees a slot from [errorSlot].
void freeErrorSlot(ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> slot) =>
    pffi.calloc.free(slot);
