// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-dev.1 (IR schema 2, runtime 0.1.0-dev.1)
// Source SDK: Apple SDK fixture
// Derived from SDK metadata installed on the build machine; see
// docs/legal/source-provenance.md before redistributing.

/// Runtime helpers for the generated Apple bindings.
library;

import 'dart:ffi' as ffi;

import 'package:ffi/ffi.dart' as pffi;
import 'package:objective_c/objective_c.dart' as objc;

/// An Objective-C `NSError` reported through an `NSError **` out-parameter.
final class NativeObjCError implements Exception {
  /// Creates an error.
  const NativeObjCError(this.domain, this.code, this.description);

  /// Copies the fields of [error].
  factory NativeObjCError.fromNSError(objc.NSError error) => NativeObjCError(
    error.domain.toDartString(),
    error.code,
    error.localizedDescription.toDartString(),
  );

  /// `NSError.domain`.
  final String domain;

  /// `NSError.code`.
  final int code;

  /// `NSError.localizedDescription`.
  final String description;

  @override
  String toString() => 'NativeObjCError($domain, $code): $description';
}

/// Allocates a zeroed `NSError *` slot for an out-parameter.
ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> errorSlot() =>
    pffi.calloc<ffi.Pointer<objc.ObjCObjectImpl>>();

/// Throws [NativeObjCError] when the call [failed] and set the slot.
/// Cocoa only defines the out-parameter when the return value reports
/// failure (`NO` or `nil`), so the slot is ignored otherwise.
void throwIfError(
  ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> slot, {
  required bool failed,
}) {
  if (!failed || slot.value.address == 0) return;
  throw NativeObjCError.fromNSError(
    objc.NSError.fromPointer(slot.value, retain: true, release: true),
  );
}

/// Frees a slot from [errorSlot].
void freeErrorSlot(ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> slot) =>
    pffi.calloc.free(slot);
