// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-beta.1 (IR schema 2, runtime 0.1.0-beta.1)
// Source SDK: Apple SDK fixture
// Derived from SDK metadata installed on the build machine; see
// docs/legal/source-provenance.md before redistributing.

// ignore_for_file: camel_case_types, comment_references, constant_identifier_names, deprecated_member_use_from_same_package, invalid_use_of_internal_member, library_prefixes, non_constant_identifier_names, no_leading_underscores_for_local_identifiers, public_member_api_docs, unused_element, unused_import, unused_field, lines_longer_than_80_chars, sort_constructors_first, unnecessary_this

/// Bindings for the `NABFixtures` module.
library;

import 'dart:async' as async;
import 'dart:ffi' as ffi;

import 'package:objective_c/objective_c.dart' as objc;

import '_blocks.dart' as bk;
import '_msgsend.dart' as ms;
import '_runtime.dart' as rt;

final _class_NABBlocks = objc.getClass('NABBlocks');
final _class_NABMainActorView = objc.getClass('NABMainActorView');
final _class_NABThing = objc.getClass('NABThing');
final _sel_addItem_ = objc.registerName('addItem:');
final _sel_addItem_atIndex_ = objc.registerName('addItem:atIndex:');
final _sel_alloc = objc.registerName('alloc');
final _sel_alpha = objc.registerName('alpha');
final _sel_centerOf_ = objc.registerName('centerOf:');
final _sel_conformsToProtocol_ = objc.registerName('conformsToProtocol:');
final _sel_count = objc.registerName('count');
final _sel_counts = objc.registerName('counts');
final _sel_describe = objc.registerName('describe');
final _sel_enumerate_with_ = objc.registerName('enumerate:with:');
final _sel_frame = objc.registerName('frame');
final _sel_identifier = objc.registerName('identifier');
final _sel_init = objc.registerName('init');
final _sel_initWithName_ = objc.registerName('initWithName:');
final _sel_instances = objc.registerName('instances');
final _sel_isKindOfClass_ = objc.registerName('isKindOfClass:');
final _sel_items = objc.registerName('items');
final _sel_legacy = objc.registerName('legacy');
final _sel_listener = objc.registerName('listener');
final _sel_mode = objc.registerName('mode');
final _sel_name = objc.registerName('name');
final _sel_new = objc.registerName('new');
final _sel_objectForKeyedSubscript_ = objc.registerName('objectForKeyedSubscript:');
final _sel_redraw = objc.registerName('redraw');
final _sel_refreshUI = objc.registerName('refreshUI');
final _sel_runAfter_completion_ = objc.registerName('runAfter:completion:');
final _sel_runWithCompletion_ = objc.registerName('runWithCompletion:');
final _sel_saveToPath_error_ = objc.registerName('saveToPath:error:');
final _sel_setAlpha_ = objc.registerName('setAlpha:');
final _sel_setFrame_ = objc.registerName('setFrame:');
final _sel_setListener_ = objc.registerName('setListener:');
final _sel_setMode_ = objc.registerName('setMode:');
final _sel_setName_ = objc.registerName('setName:');
final _sel_shouldStop = objc.registerName('shouldStop');
final _sel_stopWithCompletion_ = objc.registerName('stopWithCompletion:');
final _sel_sumWith_ = objc.registerName('sumWith:');
final _sel_thing_didChangeValue_ = objc.registerName('thing:didChangeValue:');
final _sel_thingWithValue_ = objc.registerName('thingWithValue:');
final _sel_transform_using_ = objc.registerName('transform:using:');

/// Objective-C: `@interface NABBlocks`
extension type NABBlocks._(objc.ObjCObject object$) implements objc.ObjCObject {
  /// Views [other] as `NABBlocks` (unchecked; see [isA]).
  NABBlocks.as(objc.ObjCObject other) : object$ = other;

  /// Wraps a raw object pointer.
  NABBlocks.fromPointer(ffi.Pointer<objc.ObjCObjectImpl> other, {bool retain = false, bool release = false})
    : object$ = objc.ObjCObject(other, retain: retain, release: release);

  /// Whether [obj] is an instance of `NABBlocks` (or a subclass).
  static bool isA(objc.ObjCObject? obj) =>
      obj == null ? false : ms.msgSend_xn3eu2m4e7c4(obj.ref.pointer, _sel_isKindOfClass_, _class_NABBlocks);

  /// `+alloc` (owned).
  static NABBlocks alloc() => NABBlocks.fromPointer(ms.msgSend_nwlodbzk5001(_class_NABBlocks, _sel_alloc), retain: false, release: true);

  /// `+new` (owned).
  static NABBlocks new$() => NABBlocks.fromPointer(ms.msgSend_nwlodbzk5001(_class_NABBlocks, _sel_new), retain: false, release: true);

  /// Objective-C: `-[NABBlocks enumerate:with:]`
  void enumerate(int count, {required void Function(int, ffi.Pointer<ffi.Bool>) with$}) {
    final $b1 = bk.sync_wyw89bm4fawo((int a0, ffi.Pointer<ffi.Bool> a1) { with$(a0, a1); });
    ms.msgSend_1g7mnr4uasgrf(object$.ref.pointer, _sel_enumerate_with_, count, $b1.ref.pointer.cast<objc.ObjCObjectImpl>());
  }

  /// Objective-C: `-[NABBlocks runAfter:completion:]`
  void runAfter(double seconds, {required void Function(bool, int) completion}) {
    final $b1 = bk.listener_1jxrv3498gv8s((bool a0, int a1) { completion(a0, a1); }, once: true);
    ms.msgSend_glgo9uc0wazo(object$.ref.pointer, _sel_runAfter_completion_, seconds, $b1.ref.pointer.cast<objc.ObjCObjectImpl>());
  }

  /// `Future` form of [runAfter]: completes when `completion` is called.
  async.Future<(bool, int)> runAfterAsync(double seconds) {
    final c = async.Completer<(bool, int)>();
    this.runAfter(seconds, completion: (v0, v1) { c.complete((v0, v1)); });
    return c.future;
  }

  /// Objective-C: `-[NABBlocks stopWithCompletion:]`
  void stopWithCompletion(void Function()? completion) {
    final $b0 = completion == null ? null : bk.listener_s185jcjjbqd(() { completion(); }, once: true);
    ms.msgSend_18nt33llhc07u(object$.ref.pointer, _sel_stopWithCompletion_, $b0?.ref.pointer.cast<objc.ObjCObjectImpl>() ?? ffi.nullptr);
  }

  /// `Future` form of [stopWithCompletion]: completes when `completion` is called.
  async.Future<void> stopWithCompletionAsync() {
    final c = async.Completer<void>();
    this.stopWithCompletion(() { c.complete(); });
    return c.future;
  }

  /// Objective-C: `-[NABBlocks sumWith:]`
  int sumWith(int Function(int, int) op) {
    final $b0 = bk.sync_1g5gri0bovfu1((int a0, int a1) => op(a0, a1));
    return ms.msgSend_knciohuav7c3(object$.ref.pointer, _sel_sumWith_, $b0.ref.pointer.cast<objc.ObjCObjectImpl>());
  }

  /// Objective-C: `-[NABBlocks transform:using:]`
  objc.NSString transform(objc.NSString input, {required objc.NSString Function(objc.NSString) using}) {
    final $b1 = bk.sync_mqz3yl480vdr((ffi.Pointer<objc.ObjCObjectImpl> a0) => using(objc.NSString.fromPointer(a0, retain: true, release: true)).ref.retainAndAutorelease());
    final $ret = ms.msgSend_9jksk4ebvvjv(object$.ref.pointer, _sel_transform_using_, input.ref.pointer, $b1.ref.pointer.cast<objc.ObjCObjectImpl>());
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

/// Native API: `NABFixtures.NABFlags`
abstract final class NABFlags {
  /// Native API: `NABFixtures.NABFlags#NABFlagsNone`
  static const int NABFlagsNone = 0;
  /// Native API: `NABFixtures.NABFlags#NABFlagsA`
  static const int NABFlagsA = 1;
  /// Native API: `NABFixtures.NABFlags#NABFlagsB`
  static const int NABFlagsB = 2;
  /// Native API: `NABFixtures.NABFlags#NABFlagsHigh`
  static const int NABFlagsHigh = -9223372036854775808;
}

/// Objective-C: `@protocol NABListener`
/// - Note E004 UNSUPPORTED_CALLBACK: Implementing Objective-C protocols in Dart is not supported by the Flutter iOS target yet; the protocol is usable for typing and calling
extension type NABListener._(objc.ObjCObject object$) implements objc.ObjCObject {
  /// Views [other] as `NABListener` (unchecked; see [isA]).
  NABListener.as(objc.ObjCObject other) : object$ = other;

  /// Wraps a raw object pointer.
  NABListener.fromPointer(ffi.Pointer<objc.ObjCObjectImpl> other, {bool retain = false, bool release = false})
    : object$ = objc.ObjCObject(other, retain: retain, release: release);

  /// Whether [obj] conforms to `<NABListener>`.
  static bool conformsTo(objc.ObjCObject obj) =>
      ms.msgSend_xn3eu2m4e7c4(obj.ref.pointer, _sel_conformsToProtocol_, objc.getProtocol('NABListener').cast());

  /// Objective-C: `-[NABListener shouldStop]`
  bool shouldStop() {
    return ms.msgSend_1uod87wdycb99(object$.ref.pointer, _sel_shouldStop);
  }

  /// Objective-C: `-[NABListener thing:didChangeValue:]`
  void thing(objc.ObjCObject thing, {required int didChangeValue}) {
    ms.msgSend_xvosjbsp7ajc(object$.ref.pointer, _sel_thing_didChangeValue_, thing.ref.pointer, didChangeValue);
  }
}

/// Objective-C: `@interface NABMainActorView`
/// - Threading: main actor (`NS_SWIFT_UI_ACTOR`): call on the main thread (the root isolate on iOS); checked in debug builds
/// - Note E013 THREADING_CONSTRAINT: Main actor (NS_SWIFT_UI_ACTOR): members must be called on the main thread unless marked nonisolated
extension type NABMainActorView._(objc.ObjCObject object$) implements objc.ObjCObject {
  /// Views [other] as `NABMainActorView` (unchecked; see [isA]).
  NABMainActorView.as(objc.ObjCObject other) : object$ = other;

  /// Wraps a raw object pointer.
  NABMainActorView.fromPointer(ffi.Pointer<objc.ObjCObjectImpl> other, {bool retain = false, bool release = false})
    : object$ = objc.ObjCObject(other, retain: retain, release: release);

  /// Whether [obj] is an instance of `NABMainActorView` (or a subclass).
  static bool isA(objc.ObjCObject? obj) =>
      obj == null ? false : ms.msgSend_xn3eu2m4e7c4(obj.ref.pointer, _sel_isKindOfClass_, _class_NABMainActorView);

  /// `+alloc` (owned).
  static NABMainActorView alloc() => NABMainActorView.fromPointer(ms.msgSend_nwlodbzk5001(_class_NABMainActorView, _sel_alloc), retain: false, release: true);

  /// `+new` (owned).
  static NABMainActorView new$() => NABMainActorView.fromPointer(ms.msgSend_nwlodbzk5001(_class_NABMainActorView, _sel_new), retain: false, release: true);

  /// Objective-C: `@property alpha (readwrite)`
  /// - Threading: main actor (`NS_SWIFT_UI_ACTOR`): call on the main thread (the root isolate on iOS); checked in debug builds
  double get alpha {
    assert(rt.checkMainThread("-[NABMainActorView alpha]"));
    return objc.useMsgSendVariants ? ms.msgSend_my4pkiy7h65sV(object$.ref.pointer, _sel_alpha) : ms.msgSend_my4pkiy7h65s(object$.ref.pointer, _sel_alpha);
  }

  set alpha(double value) {
    assert(rt.checkMainThread("-[NABMainActorView setAlpha:]"));
    ms.msgSend_7f9p6nk7ezol(object$.ref.pointer, _sel_setAlpha_, value);
  }

  /// Objective-C: `-[NABMainActorView identifier]`
  /// - Threading: nonisolated (callable from any thread)
  objc.NSString identifier() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_identifier);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABMainActorView redraw]`
  /// - Threading: main actor (`NS_SWIFT_UI_ACTOR`): call on the main thread (the root isolate on iOS); checked in debug builds
  void redraw() {
    assert(rt.checkMainThread("-[NABMainActorView redraw]"));
    ms.msgSend_1ivg14d6tnza3(object$.ref.pointer, _sel_redraw);
  }
}

/// Native API: `NABFixtures.NABMode`
abstract final class NABMode {
  /// Native API: `NABFixtures.NABMode#NABModeOff`
  static const int NABModeOff = 0;
  /// Native API: `NABFixtures.NABMode#NABModeOn`
  static const int NABModeOn = 1;
  /// Native API: `NABFixtures.NABMode#NABModeAuto`
  /// - iOS 15+ (guarded at runtime)
  static const int NABModeAuto = 2;
}

/// Native API: `NABFixtures.NABPoint`
final class NABPoint extends ffi.Struct {
  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;

}

/// Native API: `NABFixtures.NABRect`
final class NABRect extends ffi.Struct {
  external NABPoint origin;

  external NABPoint size;

}

/// Objective-C: `@interface NABThing`
/// - iOS 13+
extension type NABThing._(objc.ObjCObject object$) implements objc.ObjCObject {
  /// Views [other] as `NABThing` (unchecked; see [isA]).
  NABThing.as(objc.ObjCObject other) : object$ = other;

  /// Wraps a raw object pointer.
  NABThing.fromPointer(ffi.Pointer<objc.ObjCObjectImpl> other, {bool retain = false, bool release = false})
    : object$ = objc.ObjCObject(other, retain: retain, release: release);

  /// Whether [obj] is an instance of `NABThing` (or a subclass).
  static bool isA(objc.ObjCObject? obj) =>
      obj == null ? false : ms.msgSend_xn3eu2m4e7c4(obj.ref.pointer, _sel_isKindOfClass_, _class_NABThing);

  /// `+alloc` (owned).
  static NABThing alloc() => NABThing.fromPointer(ms.msgSend_nwlodbzk5001(_class_NABThing, _sel_alloc), retain: false, release: true);

  /// `+new` (owned).
  static NABThing new$() => NABThing.fromPointer(ms.msgSend_nwlodbzk5001(_class_NABThing, _sel_new), retain: false, release: true);

  /// Objective-C: `@property count (readonly)`
  /// - iOS 13+
  int get count {
    return ms.msgSend_gbtzsfs4mobu(object$.ref.pointer, _sel_count);
  }

  /// Objective-C: `@property frame (readwrite)`
  /// - iOS 13+
  NABRect get frame {
    return objc.useMsgSendVariants ? ms.msgSend_qgccgr9z8z55V(object$.ref.pointer, _sel_frame) : ms.msgSend_qgccgr9z8z55(object$.ref.pointer, _sel_frame);
  }

  set frame(NABRect value) {
    ms.msgSend_2te94355k75k(object$.ref.pointer, _sel_setFrame_, value);
  }

  /// Objective-C: `@property listener (readwrite)`
  /// - iOS 13+
  NABListener? get listener {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_listener);
    return $ret.address == 0 ? null : NABListener.fromPointer($ret, retain: true, release: true);
  }

  set listener(NABListener? value) {
    ms.msgSend_18nt33llhc07u(object$.ref.pointer, _sel_setListener_, value?.ref.pointer ?? ffi.nullptr);
  }

  /// Objective-C: `@property mode (readwrite)`
  /// - iOS 13+
  int get mode {
    return ms.msgSend_gbtzsfs4mobu(object$.ref.pointer, _sel_mode);
  }

  set mode(int value) {
    ms.msgSend_u61btxx1v205(object$.ref.pointer, _sel_setMode_, value);
  }

  /// Objective-C: `@property name (readwrite)`
  /// - iOS 13+
  objc.NSString? get name {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_name);
    return $ret.address == 0 ? null : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  set name(objc.NSString? value) {
    ms.msgSend_18nt33llhc07u(object$.ref.pointer, _sel_setName_, value?.ref.pointer ?? ffi.nullptr);
  }

  /// Objective-C: `-[NABThing addItem:]`
  /// - iOS 13+
  void addItem(objc.NSString item) {
    ms.msgSend_18nt33llhc07u(object$.ref.pointer, _sel_addItem_, item.ref.pointer);
  }

  /// Objective-C: `-[NABThing addItem:atIndex:]`
  /// - iOS 13+
  /// - Selector mapped to `addItem$atIndex`
  void addItem$atIndex(objc.NSString item, {required int atIndex}) {
    ms.msgSend_1jyp6rf45euqn(object$.ref.pointer, _sel_addItem_atIndex_, item.ref.pointer, atIndex);
  }

  /// Objective-C: `-[NABThing centerOf:]`
  /// - iOS 13+
  NABPoint centerOf(NABRect rect) {
    return ms.msgSend_1sf33yvv0kaxy(object$.ref.pointer, _sel_centerOf_, rect);
  }

  /// Objective-C: `-[NABThing counts]`
  /// - iOS 13+
  objc.NSDictionary counts() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_counts);
    return objc.NSDictionary.fromPointer($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABThing describe]`
  /// - iOS 13+
  objc.NSString describe() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_describe);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABThing init]`
  /// - iOS 13+
  NABThing init() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.retainAndReturnPointer(), _sel_init);
    return NABThing.fromPointer($ret, retain: false, release: true);
  }

  /// Objective-C: `-[NABThing initWithName:]`
  /// - iOS 13+
  NABThing initWithName(objc.NSString name) {
    final $ret = ms.msgSend_z20u32u3cw8g(object$.ref.retainAndReturnPointer(), _sel_initWithName_, name.ref.pointer);
    return NABThing.fromPointer($ret, retain: false, release: true);
  }

  /// Objective-C: `-[NABThing items]`
  /// - iOS 13+
  objc.NSArray items() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_items);
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABThing legacy]`
  /// - iOS 13+
  /// - Deprecated in iOS 15
  @Deprecated('Deprecated in iOS 15')
  void legacy() {
    ms.msgSend_1ivg14d6tnza3(object$.ref.pointer, _sel_legacy);
  }

  /// Objective-C: `-[NABThing objectForKeyedSubscript:]`
  /// - iOS 13+
  objc.ObjCObject? objectForKeyedSubscript(objc.NSString key) {
    final $ret = ms.msgSend_z20u32u3cw8g(object$.ref.pointer, _sel_objectForKeyedSubscript_, key.ref.pointer);
    return $ret.address == 0 ? null : objc.ObjCObject($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABThing refreshUI]`
  /// - iOS 13+
  /// - Threading: main actor (`NS_SWIFT_UI_ACTOR`): call on the main thread (the root isolate on iOS); checked in debug builds
  /// - Note E013 THREADING_CONSTRAINT: Main actor (NS_SWIFT_UI_ACTOR): call on the main thread
  void refreshUI() {
    assert(rt.checkMainThread("-[NABThing refreshUI]"));
    ms.msgSend_1ivg14d6tnza3(object$.ref.pointer, _sel_refreshUI);
  }

  /// Objective-C: `-[NABThing runWithCompletion:]`
  /// - iOS 16+ (guarded at runtime)
  void runWithCompletion(void Function(bool) completion) {
    objc.checkOsVersionInternal("NABThing.runWithCompletion:", iOS: (false, (16, 0, 0)));
    final $b0 = bk.listener_olxutvjws7l6((bool a0) { completion(a0); }, once: true);
    ms.msgSend_18nt33llhc07u(object$.ref.pointer, _sel_runWithCompletion_, $b0.ref.pointer.cast<objc.ObjCObjectImpl>());
  }

  /// `Future` form of [runWithCompletion]: completes when `completion` is called.
  async.Future<bool> runWithCompletionAsync() {
    final c = async.Completer<bool>();
    this.runWithCompletion((v0) { c.complete(v0); });
    return c.future;
  }

  /// Objective-C: `-[NABThing saveToPath:error:]`
  /// - iOS 13+
  bool saveToPath(objc.NSString path) {
    final $err = rt.errorSlot();
    try {
      final $ret = ms.msgSend_11zzw0qja68s1(object$.ref.pointer, _sel_saveToPath_error_, path.ref.pointer, $err);
      rt.throwIfError($err, failed: !$ret);
      return $ret;
    } finally {
      rt.freeErrorSlot($err);
    }
  }

  /// Objective-C: `@property instances (readonly)`
  /// - iOS 13+
  static int get instances {
    return ms.msgSend_14zdvslalwk0j(_class_NABThing, _sel_instances);
  }

  /// Objective-C: `+[NABThing thingWithValue:]`
  /// - iOS 13+
  static NABThing? thingWithValue(double value) {
    final $ret = ms.msgSend_1n47mp46hjv4v(_class_NABThing, _sel_thingWithValue_, value);
    return $ret.address == 0 ? null : NABThing.fromPointer($ret, retain: true, release: true);
  }
}
