// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-dev.1 (IR schema 2, runtime 0.1.0-dev.1)
// Source SDK: Apple SDK fixture
// Derived from SDK metadata installed on the build machine; see
// docs/legal/source-provenance.md before redistributing.

// ignore_for_file: camel_case_types, comment_references, constant_identifier_names, deprecated_member_use_from_same_package, invalid_use_of_internal_member, library_prefixes, non_constant_identifier_names, no_leading_underscores_for_local_identifiers, public_member_api_docs, unused_element, unused_import, unused_field, lines_longer_than_80_chars, sort_constructors_first

/// Bindings for the `NABFixtures` module.
library;

import 'dart:ffi' as ffi;

import 'package:objective_c/objective_c.dart' as objc;

import '_msgsend.dart' as ms;
import '_runtime.dart' as rt;

final _class_NABThing = objc.getClass('NABThing');
final _sel_addItem_ = objc.registerName('addItem:');
final _sel_addItem_atIndex_ = objc.registerName('addItem:atIndex:');
final _sel_alloc = objc.registerName('alloc');
final _sel_centerOf_ = objc.registerName('centerOf:');
final _sel_conformsToProtocol_ = objc.registerName('conformsToProtocol:');
final _sel_count = objc.registerName('count');
final _sel_counts = objc.registerName('counts');
final _sel_describe = objc.registerName('describe');
final _sel_frame = objc.registerName('frame');
final _sel_init = objc.registerName('init');
final _sel_initWithName_ = objc.registerName('initWithName:');
final _sel_instances = objc.registerName('instances');
final _sel_isKindOfClass_ = objc.registerName('isKindOfClass:');
final _sel_items = objc.registerName('items');
final _sel_legacy = objc.registerName('legacy');
final _sel_listener = objc.registerName('listener');
final _sel_mode = objc.registerName('mode');
final _sel_name = objc.registerName('name');
final _sel_new = objc.registerName('new');
final _sel_objectForKeyedSubscript_ = objc.registerName('objectForKeyedSubscript:');
final _sel_saveToPath_error_ = objc.registerName('saveToPath:error:');
final _sel_setFrame_ = objc.registerName('setFrame:');
final _sel_setListener_ = objc.registerName('setListener:');
final _sel_setMode_ = objc.registerName('setMode:');
final _sel_setName_ = objc.registerName('setName:');
final _sel_shouldStop = objc.registerName('shouldStop');
final _sel_thing_didChangeValue_ = objc.registerName('thing:didChangeValue:');
final _sel_thingWithValue_ = objc.registerName('thingWithValue:');

/// Native API: `NABFixtures.NABFlags`
abstract final class NABFlags {
  /// Native API: `NABFixtures.NABFlags#NABFlagsNone`
  static const int NABFlagsNone = 0;
  /// Native API: `NABFixtures.NABFlags#NABFlagsA`
  static const int NABFlagsA = 1;
  /// Native API: `NABFixtures.NABFlags#NABFlagsB`
  static const int NABFlagsB = 2;
  /// Native API: `NABFixtures.NABFlags#NABFlagsHigh`
  static const int NABFlagsHigh = -9223372036854775808;
}

/// Objective-C: `@protocol NABListener`
/// - Note E004 UNSUPPORTED_CALLBACK: Implementing Objective-C protocols in Dart is not supported by the Flutter iOS target yet; the protocol is usable for typing and calling
extension type NABListener._(objc.ObjCObject object$) implements objc.ObjCObject {
  /// Views [other] as `NABListener` (unchecked; see [isA]).
  NABListener.as(objc.ObjCObject other) : object$ = other;

  /// Wraps a raw object pointer.
  NABListener.fromPointer(ffi.Pointer<objc.ObjCObjectImpl> other, {bool retain = false, bool release = false})
    : object$ = objc.ObjCObject(other, retain: retain, release: release);

  /// Whether [obj] conforms to `<NABListener>`.
  static bool conformsTo(objc.ObjCObject obj) =>
      ms.msgSend_xn3eu2m4e7c4(obj.ref.pointer, _sel_conformsToProtocol_, objc.getProtocol('NABListener').cast());

  /// Objective-C: `-[NABListener shouldStop]`
  bool shouldStop() {
    return ms.msgSend_1uod87wdycb99(object$.ref.pointer, _sel_shouldStop);
  }

  /// Objective-C: `-[NABListener thing:didChangeValue:]`
  void thing(objc.ObjCObject thing, {required int didChangeValue}) {
    ms.msgSend_xvosjbsp7ajc(object$.ref.pointer, _sel_thing_didChangeValue_, thing.ref.pointer, didChangeValue);
  }
}

/// Native API: `NABFixtures.NABMode`
abstract final class NABMode {
  /// Native API: `NABFixtures.NABMode#NABModeOff`
  static const int NABModeOff = 0;
  /// Native API: `NABFixtures.NABMode#NABModeOn`
  static const int NABModeOn = 1;
  /// Native API: `NABFixtures.NABMode#NABModeAuto`
  /// - iOS 15+ (guarded at runtime)
  static const int NABModeAuto = 2;
}

/// Native API: `NABFixtures.NABPoint`
final class NABPoint extends ffi.Struct {
  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;

}

/// Native API: `NABFixtures.NABRect`
final class NABRect extends ffi.Struct {
  external NABPoint origin;

  external NABPoint size;

}

/// Objective-C: `@interface NABThing`
/// - iOS 13+
extension type NABThing._(objc.ObjCObject object$) implements objc.ObjCObject {
  /// Views [other] as `NABThing` (unchecked; see [isA]).
  NABThing.as(objc.ObjCObject other) : object$ = other;

  /// Wraps a raw object pointer.
  NABThing.fromPointer(ffi.Pointer<objc.ObjCObjectImpl> other, {bool retain = false, bool release = false})
    : object$ = objc.ObjCObject(other, retain: retain, release: release);

  /// Whether [obj] is an instance of `NABThing` (or a subclass).
  static bool isA(objc.ObjCObject? obj) =>
      obj == null ? false : ms.msgSend_xn3eu2m4e7c4(obj.ref.pointer, _sel_isKindOfClass_, _class_NABThing);

  /// `+alloc` (owned).
  static NABThing alloc() => NABThing.fromPointer(ms.msgSend_nwlodbzk5001(_class_NABThing, _sel_alloc), retain: false, release: true);

  /// `+new` (owned).
  static NABThing new$() => NABThing.fromPointer(ms.msgSend_nwlodbzk5001(_class_NABThing, _sel_new), retain: false, release: true);

  /// Objective-C: `@property count (readonly)`
  /// - iOS 13+
  int get count {
    return ms.msgSend_gbtzsfs4mobu(object$.ref.pointer, _sel_count);
  }

  /// Objective-C: `@property frame (readwrite)`
  /// - iOS 13+
  NABRect get frame {
    return objc.useMsgSendVariants ? ms.msgSend_qgccgr9z8z55V(object$.ref.pointer, _sel_frame) : ms.msgSend_qgccgr9z8z55(object$.ref.pointer, _sel_frame);
  }

  set frame(NABRect value) {
    ms.msgSend_2te94355k75k(object$.ref.pointer, _sel_setFrame_, value);
  }

  /// Objective-C: `@property listener (readwrite)`
  /// - iOS 13+
  NABListener? get listener {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_listener);
    return $ret.address == 0 ? null : NABListener.fromPointer($ret, retain: true, release: true);
  }

  set listener(NABListener? value) {
    ms.msgSend_18nt33llhc07u(object$.ref.pointer, _sel_setListener_, value?.ref.pointer ?? ffi.nullptr);
  }

  /// Objective-C: `@property mode (readwrite)`
  /// - iOS 13+
  int get mode {
    return ms.msgSend_gbtzsfs4mobu(object$.ref.pointer, _sel_mode);
  }

  set mode(int value) {
    ms.msgSend_u61btxx1v205(object$.ref.pointer, _sel_setMode_, value);
  }

  /// Objective-C: `@property name (readwrite)`
  /// - iOS 13+
  objc.NSString? get name {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_name);
    return $ret.address == 0 ? null : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  set name(objc.NSString? value) {
    ms.msgSend_18nt33llhc07u(object$.ref.pointer, _sel_setName_, value?.ref.pointer ?? ffi.nullptr);
  }

  /// Objective-C: `-[NABThing addItem:]`
  /// - iOS 13+
  void addItem(objc.NSString item) {
    ms.msgSend_18nt33llhc07u(object$.ref.pointer, _sel_addItem_, item.ref.pointer);
  }

  /// Objective-C: `-[NABThing addItem:atIndex:]`
  /// - iOS 13+
  /// - Selector mapped to `addItem$atIndex`
  void addItem$atIndex(objc.NSString item, {required int atIndex}) {
    ms.msgSend_1jyp6rf45euqn(object$.ref.pointer, _sel_addItem_atIndex_, item.ref.pointer, atIndex);
  }

  /// Objective-C: `-[NABThing centerOf:]`
  /// - iOS 13+
  NABPoint centerOf(NABRect rect) {
    return ms.msgSend_1sf33yvv0kaxy(object$.ref.pointer, _sel_centerOf_, rect);
  }

  /// Objective-C: `-[NABThing counts]`
  /// - iOS 13+
  objc.NSDictionary counts() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_counts);
    return objc.NSDictionary.fromPointer($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABThing describe]`
  /// - iOS 13+
  objc.NSString describe() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_describe);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABThing init]`
  /// - iOS 13+
  NABThing init() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.retainAndReturnPointer(), _sel_init);
    return NABThing.fromPointer($ret, retain: false, release: true);
  }

  /// Objective-C: `-[NABThing initWithName:]`
  /// - iOS 13+
  NABThing initWithName(objc.NSString name) {
    final $ret = ms.msgSend_z20u32u3cw8g(object$.ref.retainAndReturnPointer(), _sel_initWithName_, name.ref.pointer);
    return NABThing.fromPointer($ret, retain: false, release: true);
  }

  /// Objective-C: `-[NABThing items]`
  /// - iOS 13+
  objc.NSArray items() {
    final $ret = ms.msgSend_nwlodbzk5001(object$.ref.pointer, _sel_items);
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABThing legacy]`
  /// - iOS 13+
  /// - Deprecated in iOS 15
  @Deprecated('Deprecated in iOS 15')
  void legacy() {
    ms.msgSend_1ivg14d6tnza3(object$.ref.pointer, _sel_legacy);
  }

  /// Objective-C: `-[NABThing objectForKeyedSubscript:]`
  /// - iOS 13+
  objc.ObjCObject? objectForKeyedSubscript(objc.NSString key) {
    final $ret = ms.msgSend_z20u32u3cw8g(object$.ref.pointer, _sel_objectForKeyedSubscript_, key.ref.pointer);
    return $ret.address == 0 ? null : objc.ObjCObject($ret, retain: true, release: true);
  }

  /// Objective-C: `-[NABThing saveToPath:error:]`
  /// - iOS 13+
  bool saveToPath(objc.NSString path) {
    final $err = rt.errorSlot();
    try {
      final $ret = ms.msgSend_11zzw0qja68s1(object$.ref.pointer, _sel_saveToPath_error_, path.ref.pointer, $err);
      rt.throwIfError($err, failed: !$ret);
      return $ret;
    } finally {
      rt.freeErrorSlot($err);
    }
  }

  /// Objective-C: `@property instances (readonly)`
  /// - iOS 13+
  static int get instances {
    return ms.msgSend_14zdvslalwk0j(_class_NABThing, _sel_instances);
  }

  /// Objective-C: `+[NABThing thingWithValue:]`
  /// - iOS 13+
  static NABThing? thingWithValue(double value) {
    final $ret = ms.msgSend_1n47mp46hjv4v(_class_NABThing, _sel_thingWithValue_, value);
    return $ret.address == 0 ? null : NABThing.fromPointer($ret, retain: true, release: true);
  }
}
