// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-dev.1 (IR schema 1, runtime 0.1.0-dev.1)
// Source SDK: fixture (synthetic test classes)
// Derived from SDK metadata installed on the build machine; see
// docs/legal/source-provenance.md before redistributing.

export * from './src/runtime';
export * from './src/generated';
