// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-dev.1: @objc adapters for the
// Objective-C-representable subset of the Swift module `NABSwiftFixtures`.
import Foundation
import NABSwiftFixtures

/// Adapter for `NABSwiftFixtures.Counter`.
@objc(NABSwiftFixtures_Counter)
public final class NABSwiftFixtures_Counter: NSObject {
    /// The adapted Swift object.
    public let wrapped: Counter

    public init(wrapped: Counter) {
        self.wrapped = wrapped
    }

    /// `var value: Int { get }`
    @objc public var value: Int {
        wrapped.value
    }

    /// `var label: String`
    @objc public var label: String {
        get { wrapped.label }
        set { wrapped.label = newValue }
    }

    /// `init(start: Int, label: String = "counter")`
    @objc(initWithStart:label:)
    public init(start: Int, label: String) {
        self.wrapped = Counter(start: start, label: label)
    }

    /// `@discardableResult func increment(by step: Int) -> Int`
    @objc(incrementBy:)
    public func increment(by step: Int) -> Int {
        return wrapped.increment(by: step)
    }

    /// `func describe(prefix: String?) -> String`
    @objc(describePrefix:)
    public func describe(prefix: String?) -> String {
        return wrapped.describe(prefix: prefix)
    }

    /// `func temperature() -> Temperature`
    @objc(temperature)
    public func temperature() -> NABSwiftFixtures_Temperature {
        return NABSwiftFixtures_Temperature(wrapped: wrapped.temperature())
    }

    /// `func isAbove(_ threshold: Temperature) -> Bool`
    @objc(isAbove:)
    public func isAbove(_ threshold: NABSwiftFixtures_Temperature) -> Bool {
        return wrapped.isAbove(threshold.wrapped)
    }

    /// `static func make() -> Counter`
    @objc(make)
    public static func make() -> NABSwiftFixtures_Counter {
        return NABSwiftFixtures_Counter(wrapped: Counter.make())
    }

    /// `static var instances: Int { get }`
    @objc public static var instances: Int {
        Counter.instances
    }
}

/// Adapter for `NABSwiftFixtures.Temperature`.
@objc(NABSwiftFixtures_Temperature)
public final class NABSwiftFixtures_Temperature: NSObject {
    /// The adapted Swift value.
    public var wrapped: Temperature

    public init(wrapped: Temperature) {
        self.wrapped = wrapped
    }

    /// `var celsius: Double`
    @objc public var celsius: Double {
        get { wrapped.celsius }
        set { wrapped.celsius = newValue }
    }

    /// `init(celsius: Double)`
    @objc(initWithCelsius:)
    public init(celsius: Double) {
        self.wrapped = Temperature(celsius: celsius)
    }

    /// `var fahrenheit: Double { get }`
    @objc public var fahrenheit: Double {
        wrapped.fahrenheit
    }

    /// `func adding(_ delta: Double) -> Temperature`
    @objc(adding:)
    public func adding(_ delta: Double) -> NABSwiftFixtures_Temperature {
        return NABSwiftFixtures_Temperature(wrapped: wrapped.adding(delta))
    }

    /// `mutating func reset()`
    @objc(reset)
    public func reset() {
        wrapped.reset()
    }
}
