# GENERATED CODE - DO NOT MODIFY BY HAND.
# Generated by native-api-bindgen 0.1.0-beta.1 (IR schema 2, runtime 0.1.0-beta.1)
# Source SDK: fixture (synthetic test classes)
# Derived from SDK metadata installed on the build machine; see
# docs/legal/source-provenance.md before redistributing.

# The runtime classes are only referenced from native code.
-keep class dev.nativeapibindgen.runtime.** { *; }
# Kotlin coroutine classes used reflectively by NabContinuation.
-keep interface kotlin.coroutines.Continuation { *; }
-keep class kotlin.coroutines.EmptyCoroutineContext { *; }
-keep class kotlin.Result$Failure { *; }
-keep class kotlin.coroutines.intrinsics.CoroutineSingletons { *; }
