/// Runtime support for bindings generated by native-api-bindgen.
///
/// Generated code depends on this library for availability guards and error
/// translation. It contains no registry of generated types and performs no
/// work at startup.
library;

export 'src/android_api.dart';
export 'src/bytes.dart';
export 'src/callbacks.dart';
export 'src/errors.dart';
export 'src/handles.dart';
export 'src/kotlin.dart';
