import 'dart:collection';
import 'dart:io';

import 'package:native_api_core/native_api_core.dart';
import 'package:native_api_ir/native_api_ir.dart';
import 'package:path/path.dart' as p;

/// One generated file (path relative to the output root, `/`-separated).
final class GeneratedFile {
  /// Creates a file.
  const GeneratedFile(this.path, this.contents);

  /// Relative path.
  final String path;

  /// Contents.
  final String contents;
}

/// A generated declaration traced back to its native symbol (TRD §58, §110).
final class BindingMapEntry implements Comparable<BindingMapEntry> {
  /// Creates an entry.
  const BindingMapEntry({
    required this.symbolId,
    required this.generated,
    required this.file,
    required this.generator,
    required this.runtimeAdapter,
  });

  /// Native symbol ID.
  final String symbolId;

  /// Generated declaration, e.g. `Intent.putExtra$String$int`.
  final String generated;

  /// Output file.
  final String file;

  /// Generator that produced it, e.g. `flutter-android/dart-jni`.
  final String generator;

  /// Runtime mechanism, e.g. `package:jni JInstanceMethodId`.
  final String runtimeAdapter;

  @override
  int compareTo(BindingMapEntry o) => symbolId.compareTo(o.symbolId);

  /// JSON form.
  Map<String, Object?> toJson() => {
    'symbolId': symbolId,
    'generated': generated,
    'file': file,
    'generator': generator,
    'runtimeAdapter': runtimeAdapter,
  };
}

/// Result of a generator run.
final class GenerationOutput {
  /// Creates an output.
  GenerationOutput({
    required List<GeneratedFile> files,
    required List<BindingMapEntry> bindings,
    required this.module,
    required List<Diagnostic> diagnostics,
  }) : files = List.unmodifiable(
         files.toList()..sort((a, b) => a.path.compareTo(b.path)),
       ),
       bindings = List.unmodifiable(bindings.toList()..sort()),
       diagnostics = List.unmodifiable(diagnostics.toSet().toList()..sort());

  /// Files sorted by path.
  final List<GeneratedFile> files;

  /// Binding map sorted by symbol.
  final List<BindingMapEntry> bindings;

  /// IR annotated with this target's support decisions (used for coverage,
  /// `why-generated`, `why-skipped`).
  final ApiModule module;

  /// Run diagnostics.
  final List<Diagnostic> diagnostics;
}

/// Header placed at the top of every generated source file (TRD §93). No
/// timestamps: output must be reproducible.
String generatedHeader(ApiModule module, {String comment = '//'}) {
  final sdk = switch (module.platform) {
    ApiPlatform.android =>
      module.sdkVersion == 'fixture'
          ? 'fixture (synthetic test classes)'
          : 'Android API ${module.sdkVersion}',
    ApiPlatform.apple => 'Apple SDK ${module.sdkVersion}',
  };
  final rev = module.sourceRevision == null
      ? ''
      : ' (platform revision ${module.sourceRevision})';
  return '$comment ${ProjectInfo.generatedMarker}\n'
      '$comment Generated by ${ProjectInfo.name} ${ProjectInfo.generatorVersion} '
      '(IR schema ${ProjectInfo.irSchema}, runtime ${ProjectInfo.runtimeVersion})\n'
      '$comment Source SDK: $sdk$rev\n'
      '$comment Derived from SDK metadata installed on the build machine; see\n'
      '$comment docs/legal/source-provenance.md before redistributing.\n';
}

/// Writes [output] below [guard]'s root and removes files that a previous
/// run generated but this run did not. Only files recorded in the previous
/// manifest *and* starting with the generated marker are ever deleted.
/// Returns the list of written relative paths.
List<String> writeGeneration(
  OutputGuard guard,
  GenerationOutput output, {
  Map<String, String> extra = const {},
}) {
  const manifestName = '.native_api_bindgen_manifest';
  final manifestPath = guard.resolve(manifestName);
  final previous = File(manifestPath).existsSync()
      ? File(
          manifestPath,
        ).readAsLinesSync().where((l) => l.trim().isNotEmpty).toSet()
      : <String>{};
  final written = SplayTreeSet<String>();
  for (final f in output.files) {
    guard.writeString(f.path, f.contents);
    written.add(f.path);
  }
  extra.forEach((path, contents) {
    guard.writeString(path, contents);
    written.add(path);
  });
  for (final stale in previous.difference(written)) {
    final full = guard.resolve(stale);
    final file = File(full);
    if (file.existsSync() &&
        file.readAsStringSync().contains(ProjectInfo.generatedMarker)) {
      file.deleteSync();
    }
  }
  guard.writeString(manifestName, '${written.join('\n')}\n');
  return written.toList();
}

/// Relative import path from [fromFile] to [toFile] (both output-relative).
String relativeImport(String fromFile, String toFile) {
  final rel = p.posix.relative(toFile, from: p.posix.dirname(fromFile));
  return rel;
}

/// Escapes [s] as a Dart single-quoted string literal.
String dartStringLiteral(String s) {
  final b = StringBuffer("'");
  for (final r in s.runes) {
    switch (r) {
      case 0x5C:
        b.write(r'\\');
      case 0x27:
        b.write(r"\'");
      case 0x24:
        b.write(r'\$');
      case 0x0A:
        b.write(r'\n');
      case 0x0D:
        b.write(r'\r');
      case 0x09:
        b.write(r'\t');
      default:
        if (r < 0x20 || r == 0x7F || (r >= 0xD800 && r <= 0xDFFF)) {
          b.write('\\u{${r.toRadixString(16)}}');
        } else {
          b.writeCharCode(r);
        }
    }
  }
  b.write("'");
  return b.toString();
}
