#!/usr/bin/env python3
"""Prints the Homebrew formula for a native-api-bindgen release.

Usage: homebrew_formula.py <version> <dist-dir>

<dist-dir> holds the `*.tar.gz.sha256` files written by the release workflow
(one per target). The formula downloads the matching archive from the GitHub
Release of tag v<version>.
"""
import os
import sys

REPO = "https://github.com/lkrjangid1/native-api-bindgen"
TARGETS = ["macos-arm64", "macos-x64", "linux-arm64", "linux-x64"]


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    version, dist = sys.argv[1], sys.argv[2]
    sums = {}
    for target in TARGETS:
        name = f"native-api-bindgen-{version}-{target}.tar.gz"
        path = os.path.join(dist, name + ".sha256")
        if not os.path.exists(path):
            sys.exit(f"missing {path}")
        sums[target] = open(path).read().split()[0]

    def block(target):
        url = f"{REPO}/releases/download/v{version}/native-api-bindgen-{version}-{target}.tar.gz"
        return f'      url "{url}"\n      sha256 "{sums[target]}"'

    print(f'''# Generated by tools/homebrew_formula.py; do not edit by hand.
class NativeApiBindgen < Formula
  desc "Generate typed Flutter and React Native bindings for Android and iOS SDK APIs"
  homepage "{REPO}"
  version "{version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
{block("macos-arm64")}
    end
    on_intel do
{block("macos-x64")}
    end
  end

  on_linux do
    on_arm do
{block("linux-arm64")}
    end
    on_intel do
{block("linux-x64")}
    end
  end

  def install
    bin.install "native-api-bindgen"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/native-api-bindgen --version")
  end
end''')


if __name__ == "__main__":
    main()
