import 'dart:async';

import 'package:flutter/material.dart';

import 'showcase.dart';

void main() => runApp(const ShowcaseApp());

/// iOS tasks done entirely through bindings generated by native-api-bindgen:
/// no platform channel, no plugin per API.
class ShowcaseApp extends StatelessWidget {
  /// Creates the app.
  const ShowcaseApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
    title: 'native-api-bindgen · iOS',
    theme: ThemeData(colorSchemeSeed: Colors.indigo, useMaterial3: true),
    darkTheme: ThemeData(
      colorSchemeSeed: Colors.indigo,
      brightness: Brightness.dark,
      useMaterial3: true,
    ),
    home: const ShowcasePage(),
  );
}

/// Live device dashboard plus one card per task.
class ShowcasePage extends StatefulWidget {
  /// Creates the page.
  const ShowcasePage({super.key});

  @override
  State<ShowcasePage> createState() => _ShowcasePageState();
}

class _ShowcasePageState extends State<ShowcasePage> {
  final _text = TextEditingController(
    text: 'Hello from Dart, through generated iOS bindings.',
  );
  DeviceStatus? _status;
  String? _note;
  Timer? _timer;

  @override
  void initState() {
    super.initState();
    _refresh();
    _note = Showcase.loadNote();
    _timer = Timer.periodic(const Duration(seconds: 3), (_) => _refresh());
  }

  @override
  void dispose() {
    _timer?.cancel();
    _text.dispose();
    super.dispose();
  }

  void _refresh() => setState(() => _status = Showcase.deviceStatus());

  Future<void> _run(String label, FutureOr<String> Function() task) async {
    final messenger = ScaffoldMessenger.of(context);
    try {
      final result = await task();
      messenger.showSnackBar(SnackBar(content: Text(result)));
    } on Object catch (e) {
      messenger.showSnackBar(SnackBar(content: Text('$label failed: $e')));
    }
  }

  @override
  Widget build(BuildContext context) {
    final s = _status;
    return Scaffold(
      appBar: AppBar(title: const Text('Native iOS APIs from Dart')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          if (s != null) _Dashboard(status: s),
          const SizedBox(height: 16),
          TextField(
            controller: _text,
            minLines: 1,
            maxLines: 3,
            decoration: const InputDecoration(
              labelText: 'Text used by the tasks below',
              border: OutlineInputBorder(),
            ),
          ),
          const SizedBox(height: 16),
          _Task(
            icon: Icons.record_voice_over,
            title: 'Speak',
            api: 'AVSpeechSynthesizer + AVSpeechUtterance',
            onPressed: () => _run('Speak', () {
              Speaker.instance.speak(_text.text);
              return 'Speaking…';
            }),
          ),
          _Task(
            icon: Icons.ios_share,
            title: 'Share',
            api: 'UIActivityViewController, presented from the key window',
            onPressed: () => _run('Share', () async {
              await Showcase.share(_text.text);
              return 'Share sheet presented';
            }),
          ),
          _Task(
            icon: Icons.copy,
            title: 'Copy, then paste back',
            api: 'UIPasteboard.generalPasteboard',
            onPressed: () => _run('Clipboard', () {
              Showcase.copy(_text.text);
              return 'Pasteboard now holds: ${Showcase.paste()}';
            }),
          ),
          _Task(
            icon: Icons.save,
            title: 'Save as note',
            api: 'NSUserDefaults (survives restarts)',
            subtitle: _note == null ? 'No note saved yet' : 'Saved: $_note',
            onPressed: () => _run('Save', () {
              Showcase.saveNote(_text.text);
              setState(() => _note = Showcase.loadNote());
              return 'Note saved';
            }),
          ),
          _Task(
            icon: Icons.vibration,
            title: 'Haptics',
            api: 'UIImpactFeedbackGenerator + UINotificationFeedbackGenerator',
            onPressed: () => _run('Haptics', () async {
              await Showcase.haptics();
              return 'Impact, then success';
            }),
          ),
          _Task(
            icon: Icons.location_on,
            title: 'App settings (location permission)',
            api: 'UIApplicationOpenSettingsURLString via openURL:',
            onPressed: () => _run('App settings', () async {
              final ok = await Showcase.openAppSettings();
              return ok ? 'Settings opened' : 'Could not open Settings';
            }),
          ),
          _Task(
            icon: Icons.open_in_browser,
            title: 'Open Apple documentation',
            api:
                'UIApplication openURL:options:completionHandler: (block → Dart)',
            onPressed: () => _run('Open', () async {
              final ok = await Showcase.openUrl(
                'https://developer.apple.com/documentation/uikit',
              );
              return ok ? 'Opened in Safari' : 'Could not open the URL';
            }),
          ),
        ],
      ),
    );
  }
}

class _Dashboard extends StatelessWidget {
  const _Dashboard({required this.status});

  final DeviceStatus status;

  static String _gb(int bytes) =>
      '${(bytes / (1 << 30)).toStringAsFixed(1)} GB';

  @override
  Widget build(BuildContext context) {
    final s = status;
    final theme = Theme.of(context);
    final free = s.freeStorageBytes;
    final total = s.totalStorageBytes;
    final up = s.uptime;
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(s.device, style: theme.textTheme.titleLarge),
            Text(
              '${s.system} · refreshes every 3 s',
              style: theme.textTheme.bodySmall,
            ),
            const SizedBox(height: 16),
            _Meter(
              icon: Icons.battery_std,
              label: 'Battery',
              value: s.batteryLevel,
              detail: s.batteryLevel == null
                  ? 'not reported (simulator)'
                  : '${(s.batteryLevel! * 100).round()}% · ${s.batteryState}',
            ),
            _Meter(
              icon: Icons.sd_storage,
              label: 'Storage',
              value: free == null || total == null
                  ? null
                  : (total - free) / total,
              detail: free == null || total == null
                  ? 'unknown'
                  : '${_gb(free)} free of ${_gb(total)}',
            ),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                _Chip(Icons.thermostat, 'Thermal: ${s.thermalState}'),
                _Chip(Icons.memory, '${_gb(s.physicalMemoryBytes)} RAM'),
                _Chip(Icons.developer_board, '${s.processors} cores'),
                _Chip(
                  Icons.timer,
                  'Up ${up.inHours} h ${up.inMinutes % 60} min',
                ),
                _Chip(
                  Icons.energy_savings_leaf,
                  'Low Power Mode ${s.lowPowerMode ? 'on' : 'off'}',
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _Chip extends StatelessWidget {
  const _Chip(this.icon, this.label);

  final IconData icon;
  final String label;

  @override
  Widget build(BuildContext context) =>
      Chip(avatar: Icon(icon, size: 18), label: Text(label));
}

class _Meter extends StatelessWidget {
  const _Meter({
    required this.icon,
    required this.label,
    required this.value,
    required this.detail,
  });

  final IconData icon;
  final String label;
  final double? value;
  final String detail;

  @override
  Widget build(BuildContext context) => Padding(
    padding: const EdgeInsets.symmetric(vertical: 6),
    child: Row(
      children: [
        Icon(icon),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Text(label),
                  const Spacer(),
                  Text(detail, style: Theme.of(context).textTheme.bodySmall),
                ],
              ),
              const SizedBox(height: 4),
              LinearProgressIndicator(value: value ?? 0, minHeight: 6),
            ],
          ),
        ),
      ],
    ),
  );
}

class _Task extends StatelessWidget {
  const _Task({
    required this.icon,
    required this.title,
    required this.api,
    required this.onPressed,
    this.subtitle,
  });

  final IconData icon;
  final String title;
  final String api;
  final String? subtitle;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) => Card(
    child: ListTile(
      leading: Icon(icon),
      title: Text(title),
      subtitle: Text(subtitle == null ? api : '$api\n$subtitle'),
      isThreeLine: subtitle != null,
      trailing: const Icon(Icons.play_arrow),
      onTap: onPressed,
    ),
  );
}
