name: release-check

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/ci.yml
  generator:
    uses: ./.github/workflows/generator.yml
  android:
    uses: ./.github/workflows/android.yml
  flutter:
    uses: ./.github/workflows/flutter.yml
  license:
    uses: ./.github/workflows/license-audit.yml
  security:
    uses: ./.github/workflows/security.yml
