// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by native-api-bindgen 0.1.0-dev.1 (IR schema 2, runtime 0.1.0-dev.1)
// Source SDK: fixture (synthetic test classes)
// Derived from SDK metadata installed on the build machine; see
// docs/legal/source-provenance.md before redistributing.

// ignore_for_file: camel_case_types, comment_references, constant_identifier_names, deprecated_member_use_from_same_package, implementation_imports, invalid_use_of_internal_member, library_prefixes, non_constant_identifier_names, no_leading_underscores_for_local_identifiers, public_member_api_docs, unnecessary_cast, unnecessary_non_null_assertion, unused_element, unused_import, unused_field, lines_longer_than_80_chars, sort_constructors_first

/// Bindings for Java package `com.example.fixtures`.
library;

import 'package:jni/_internal.dart' as jnii$;
import 'package:jni/jni.dart' as jni$;
import 'package:native_api_runtime/native_api_runtime.dart' as rt$;

/// Native API: `com.example.fixtures.AnnotatedClass` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type AnnotatedClass._(jni$.JObject _$AnnotatedClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/AnnotatedClass');

  /// `package:jni` type descriptor for `com.example.fixtures.AnnotatedClass`.
  static const jni$.JType<AnnotatedClass> type = _$AnnotatedClass$Type();

  /// Native API: `com.example.fixtures.AnnotatedClass#ACTION`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `com.example.ACTION "quoted" $dollar \slash`
  static const String ACTION = 'com.example.ACTION "quoted" \$dollar \\slash';

  /// Native API: `com.example.fixtures.AnnotatedClass#BIG`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `9223372036854775807`
  static const int BIG = 9223372036854775807;

  /// Native API: `com.example.fixtures.AnnotatedClass#ENABLED`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `true`
  static const bool ENABLED = true;

  /// Native API: `com.example.fixtures.AnnotatedClass#HALF`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `0.5`
  static const double HALF = 0.5;

  /// Native API: `com.example.fixtures.AnnotatedClass#LETTER`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `120`
  static const int LETTER = 120;

  /// Native API: `com.example.fixtures.AnnotatedClass#MODE_A`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `1`
  static const int MODE_A = 1;

  /// Native API: `com.example.fixtures.AnnotatedClass#MODE_B`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `2`
  static const int MODE_B = 2;

  /// Native API: `com.example.fixtures.AnnotatedClass#TINY`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `1e-300`
  static const double TINY = 1e-300;

  /// Native API: `com.example.fixtures.AnnotatedClass#UNICODE`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `café ☃`
  static const String UNICODE = 'café ☃';

  static final _$f$counter = _$class.staticFieldId(r'counter', r'I');
  /// Native API: `com.example.fixtures.AnnotatedClass#counter`
  ///
  /// - Android API: 1+
  static int get counter {
    return _$f$counter.get(_$class, jni$.jint.type);
  }
  static set counter(int value) => _$f$counter.set(_$class, jni$.jint.type, value);

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.AnnotatedClass#<init>()`
  ///
  /// - Android API: 1+
  factory AnnotatedClass() {
    return rt$.guardJni(() => _$c$.call<AnnotatedClass>(_$class, []));
  }

  static final _$m$capture = _$class.instanceMethodId(r'capture', r'(I)V');
  /// Native API: `com.example.fixtures.AnnotatedClass#capture(int)`
  ///
  /// - Android API: 23+
  /// - Threading: call off the main thread (`@WorkerThread`)
  /// - Permissions: `anyOf:android.permission.CAMERA`, `anyOf:android.permission.RECORD_AUDIO`
  /// - Annotation: `@RequiresPermission` anyOf={android.permission.CAMERA, android.permission.RECORD_AUDIO}
  void capture(int mode) {
    rt$.guardJni(() => _$m$capture.call(this, jni$.jvoid.type, [jni$.JValueInt(mode)]));
  }

  static final _$m$old = _$class.instanceMethodId(r'old', r'()V');
  /// Native API: `com.example.fixtures.AnnotatedClass#old()`
  ///
  /// - Android API: 1+
  /// - Deprecated in Android API 30
  @Deprecated('Deprecated in Android API 30')
  void old() {
    rt$.guardJni(() => _$m$old.call(this, jni$.jvoid.type, []));
  }

  static final _$m$render = _$class.instanceMethodId(r'render', r'()V');
  /// Native API: `com.example.fixtures.AnnotatedClass#render()`
  ///
  /// - Android API: 1+
  /// - Threading: call on the main thread (`@MainThread`)
  void render() {
    rt$.guardJni(() => _$m$render.call(this, jni$.jvoid.type, []));
  }
}

final class _$AnnotatedClass$Type extends jni$.JType<AnnotatedClass> {
  const _$AnnotatedClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/AnnotatedClass;';
}

/// Native API: `com.example.fixtures.ApiLevelClass` (class)
///
/// - Android API: 5+
/// - Superclass: `java.lang.Object`
extension type ApiLevelClass._(jni$.JObject _$ApiLevelClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/ApiLevelClass');

  /// `package:jni` type descriptor for `com.example.fixtures.ApiLevelClass`.
  static const jni$.JType<ApiLevelClass> type = _$ApiLevelClass$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.ApiLevelClass#<init>()`
  ///
  /// - Android API: 5+
  factory ApiLevelClass() {
    return rt$.guardJni(() => _$c$.call<ApiLevelClass>(_$class, []));
  }

  static final _$m$since1 = _$class.instanceMethodId(r'since1', r'()V');
  /// Native API: `com.example.fixtures.ApiLevelClass#since1()`
  ///
  /// - Android API: 5+
  void since1() {
    rt$.guardJni(() => _$m$since1.call(this, jni$.jvoid.type, []));
  }

  static final _$m$since30 = _$class.instanceMethodId(r'since30', r'()V');
  /// Native API: `com.example.fixtures.ApiLevelClass#since30()`
  ///
  /// - Android API: 30+ (guarded at runtime: minApi is 24)
  /// - Deprecated in Android API 35
  @Deprecated('Deprecated in Android API 35')
  void since30() {
    rt$.AndroidApi.require(30, 0, r'com.example.fixtures.ApiLevelClass#since30()');
    rt$.guardJni(() => _$m$since30.call(this, jni$.jvoid.type, []));
  }

  static final _$m$since36minor = _$class.instanceMethodId(r'since36minor', r'()V');
  /// Native API: `com.example.fixtures.ApiLevelClass#since36minor()`
  ///
  /// - Android API: 36.1+ (guarded at runtime: minApi is 24)
  void since36minor() {
    rt$.AndroidApi.require(36, 1, r'com.example.fixtures.ApiLevelClass#since36minor()');
    rt$.guardJni(() => _$m$since36minor.call(this, jni$.jvoid.type, []));
  }

  static final _$m$unlisted = _$class.instanceMethodId(r'unlisted', r'()V');
  /// Native API: `com.example.fixtures.ApiLevelClass#unlisted()`
  ///
  /// - Android API: 5+
  /// - Note E012 AVAILABILITY_MISMATCH: Not listed in api-versions.xml (inherited from a non-public superclass); availability inferred from the declaring class
  void unlisted() {
    rt$.guardJni(() => _$m$unlisted.call(this, jni$.jvoid.type, []));
  }
}

final class _$ApiLevelClass$Type extends jni$.JType<ApiLevelClass> {
  const _$ApiLevelClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/ApiLevelClass;';
}

/// Native API: `com.example.fixtures.AsyncClass` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type AsyncClass._(jni$.JObject _$AsyncClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/AsyncClass');

  /// `package:jni` type descriptor for `com.example.fixtures.AsyncClass`.
  static const jni$.JType<AsyncClass> type = _$AsyncClass$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.AsyncClass#<init>()`
  ///
  /// - Android API: 1+
  factory AsyncClass() {
    return rt$.guardJni(() => _$c$.call<AsyncClass>(_$class, []));
  }

  static final _$m$ask = _$class.instanceMethodId(r'ask', r'(Lcom/example/fixtures/CallbackInterface;)Z');
  /// Native API: `com.example.fixtures.AsyncClass#ask(com.example.fixtures.CallbackInterface)`
  ///
  /// - Android API: 1+
  /// - `callback`: `com.example.fixtures.CallbackInterface`, nullability unknown (treated as nullable)
  bool ask(CallbackInterface? callback) {
    return rt$.guardJni(() => _$m$ask.call(this, jni$.jboolean.type, [callback]));
  }

  static final _$m$labelOf = _$class.instanceMethodId(r'labelOf', r'(Lcom/example/fixtures/CallbackInterface;)Ljava/lang/String;');
  /// Native API: `com.example.fixtures.AsyncClass#labelOf(com.example.fixtures.CallbackInterface)`
  ///
  /// - Android API: 1+
  /// - `callback`: `com.example.fixtures.CallbackInterface`, nullability unknown (treated as nullable)
  /// - Returns `java.lang.String`, nullability unknown (treated as nullable)
  String? labelOf(CallbackInterface? callback) {
    return rt$.guardJni(() => _$m$labelOf.callNullable(this, jni$.JString.type, [callback])?.toDartString(releaseOriginal: true));
  }

  static final _$m$load = _$class.instanceMethodId(r'load', r'(Ljava/lang/String;Lcom/example/fixtures/CallbackInterface;)V');
  /// Native API: `com.example.fixtures.AsyncClass#load(java.lang.String,com.example.fixtures.CallbackInterface)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - `callback`: `com.example.fixtures.CallbackInterface`, nullability unknown (treated as nullable)
  void load(String? key, CallbackInterface? callback) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$load.call(this, jni$.jvoid.type, [_$key, callback]));
    } finally {
      _$key?.release();
    }
  }

  static final _$m$loadOnThread = _$class.instanceMethodId(r'loadOnThread', r'(Ljava/lang/String;Lcom/example/fixtures/CallbackInterface;)V');
  /// Native API: `com.example.fixtures.AsyncClass#loadOnThread(java.lang.String,com.example.fixtures.CallbackInterface)`
  ///
  /// - Android API: 1+
  /// - Throws (Java): `java.lang.InterruptedException`; surfaced as `NativeJavaException`
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - `callback`: `com.example.fixtures.CallbackInterface`, nullability unknown (treated as nullable)
  void loadOnThread(String? key, CallbackInterface? callback) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$loadOnThread.call(this, jni$.jvoid.type, [_$key, callback]));
    } finally {
      _$key?.release();
    }
  }
}

final class _$AsyncClass$Type extends jni$.JType<AsyncClass> {
  const _$AsyncClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/AsyncClass;';
}

/// Native API: `com.example.fixtures.CallbackInterface` (interface)
///
/// - Android API: 1+
///
/// Implement in Dart with [CallbackInterface.implement].
extension type CallbackInterface._(jni$.JObject _$CallbackInterface) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/CallbackInterface');

  /// `package:jni` type descriptor for `com.example.fixtures.CallbackInterface`.
  static const jni$.JType<CallbackInterface> type = _$CallbackInterface$Type();

  static final _$m$label = _$class.instanceMethodId(r'label', r'()Ljava/lang/String;');
  /// Native API: `com.example.fixtures.CallbackInterface#label()`
  ///
  /// - Android API: 1+
  /// - Returns `java.lang.String`, nullability unknown (treated as nullable)
  String? label() {
    return rt$.guardJni(() => _$m$label.callNullable(this, jni$.JString.type, [])?.toDartString(releaseOriginal: true));
  }

  static final _$m$noop = _$class.staticMethodId(r'noop', r'()Lcom/example/fixtures/CallbackInterface;');
  /// Native API: `com.example.fixtures.CallbackInterface#noop()`
  ///
  /// - Android API: 1+
  /// - Returns `com.example.fixtures.CallbackInterface`, nullability unknown (treated as nullable)
  static CallbackInterface? noop() {
    return rt$.guardJni(() => _$m$noop.callNullable(_$class, CallbackInterface.type, []));
  }

  static final _$m$onEvent = _$class.instanceMethodId(r'onEvent', r'(Ljava/lang/String;I)V');
  /// Native API: `com.example.fixtures.CallbackInterface#onEvent(java.lang.String,int)`
  ///
  /// - Android API: 1+
  /// - `p0`: `java.lang.String`, non-null
  void onEvent(String p0, int p1) {
    final _$p0 = p0.toJString();
    try {
      rt$.guardJni(() => _$m$onEvent.call(this, jni$.jvoid.type, [_$p0, jni$.JValueInt(p1)]));
    } finally {
      _$p0.release();
    }
  }

  static final _$m$shouldContinue = _$class.instanceMethodId(r'shouldContinue', r'()Z');
  /// Native API: `com.example.fixtures.CallbackInterface#shouldContinue()`
  ///
  /// - Android API: 1+
  bool shouldContinue() {
    return rt$.guardJni(() => _$m$shouldContinue.call(this, jni$.jboolean.type, []));
  }

  static final Map<int, $CallbackInterface> _$impls = {};

  static jnii$.JObjectPtr _$invoke(int port, jnii$.JObjectPtr descriptor, jnii$.JObjectPtr args) {
    final $r = _$invokeMethod(port, jnii$.MethodInvocation.fromAddresses(0, descriptor.address, args.address));
    rt$.NativeCallbacks.wakeEventLoop();
    return $r;
  }

  static final jnii$.Pointer<jnii$.NativeFunction<jnii$.JObjectPtr Function(jnii$.Int64, jnii$.JObjectPtr, jnii$.JObjectPtr)>> _$invokePointer =
      jnii$.Pointer.fromFunction(_$invoke);

  static jnii$.Pointer<jnii$.Void> _$invokeMethod(int $p, jnii$.MethodInvocation $i) {
    final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
    final $a = $i.args;
    if ($d == r'label()Ljava/lang/String;') {
      try {
        final $r = _$impls[$p]!.label();
        return ($r as String?)?.toJString().reference.toPointer() ?? jnii$.nullptr;
      } catch (e, st) {
        rt$.NativeCallbacks.reportPropagated(e, st, r'com.example.fixtures.CallbackInterface#label()');
        return jnii$.ProtectedJniExtensions.newDartException(e);
      }
    }
    if ($d == r'onEvent(Ljava/lang/String;I)V') {
      try {
        _$impls[$p]!.onEvent(($a![0] as jni$.JString).toDartString(releaseOriginal: true), ($a![1] as jni$.JInteger).toDartInt(releaseOriginal: true));
        return jnii$.nullptr;
      } catch (e, st) {
        if (rt$.NativeCallbacks.handleVoidCallbackError(e, st, r'com.example.fixtures.CallbackInterface#onEvent(java.lang.String,int)')) {
          return jnii$.nullptr;
        }
        return jnii$.ProtectedJniExtensions.newDartException(e);
      }
    }
    if ($d == r'shouldContinue()Z') {
      try {
        final $r = _$impls[$p]!.shouldContinue();
        return $r.toJBoolean().reference.toPointer();
      } catch (e, st) {
        rt$.NativeCallbacks.reportPropagated(e, st, r'com.example.fixtures.CallbackInterface#shouldContinue()');
        return jnii$.ProtectedJniExtensions.newDartException(e);
      }
    }
    return jnii$.nullptr;
  }

  /// Adds a Dart implementation of `com.example.fixtures.CallbackInterface` to [implementer], for
  /// objects implementing several interfaces.
  static void implementIn(jni$.JImplementer implementer, $CallbackInterface $impl) {
    late final jnii$.RawReceivePort $p;
    $p = jnii$.RawReceivePort((Object? $m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jnii$.MethodInvocation.fromMessage($m as List<dynamic>);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jnii$.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(r'com.example.fixtures.CallbackInterface', $p, _$invokePointer, [
      if ($impl.onEvent$async) r'onEvent(Ljava/lang/String;I)V',
    ]);
    _$impls[$p.sendPort.nativePort] = $impl;
  }

  /// Creates a Java object implementing `com.example.fixtures.CallbackInterface` backed by [$impl].
  ///
  /// The Dart implementation is retained until the Java proxy is
  /// garbage-collected. A `void` callback that throws is reported through
  /// `NativeCallbacks` instead of crashing the calling Java thread.
  factory CallbackInterface.implement($CallbackInterface $impl) {
    final $i = jni$.JImplementer();
    implementIn($i, $impl);
    return $i.implement<CallbackInterface>();
  }
}

final class _$CallbackInterface$Type extends jni$.JType<CallbackInterface> {
  const _$CallbackInterface$Type();

  @override
  String get signature => r'Lcom/example/fixtures/CallbackInterface;';
}

/// Dart implementation of `com.example.fixtures.CallbackInterface`; see [CallbackInterface.implement].
abstract base mixin class $CallbackInterface {
  factory $CallbackInterface({
    required String? Function() label,
    required void Function(String p0, int p1) onEvent,
    bool onEvent$async,
    required bool Function() shouldContinue,
  }) = _$CallbackInterface;

  /// Implements `com.example.fixtures.CallbackInterface#label()`.
  String? label();

  /// Implements `com.example.fixtures.CallbackInterface#onEvent(java.lang.String,int)`.
  void onEvent(String p0, int p1);

  /// Whether Java calls to [onEvent] return without waiting for Dart.
  bool get onEvent$async => false;

  /// Implements `com.example.fixtures.CallbackInterface#shouldContinue()`.
  bool shouldContinue();

}

final class _$CallbackInterface with $CallbackInterface {
  _$CallbackInterface({
    required String? Function() label,
    required void Function(String p0, int p1) onEvent,
    this.onEvent$async = false,
    required bool Function() shouldContinue,
  }) : _label = label, _onEvent = onEvent, _shouldContinue = shouldContinue;

  final String? Function() _label;
  @override
  String? label() => _label();

  final void Function(String p0, int p1) _onEvent;
  @override
  final bool onEvent$async;
  @override
  void onEvent(String p0, int p1) => _onEvent(p0, p1);

  final bool Function() _shouldContinue;
  @override
  bool shouldContinue() => _shouldContinue();

}

/// Native API: `com.example.fixtures.Countable` (interface)
///
/// - Android API: 1+
///
/// Implement in Dart with [Countable.implement].
extension type Countable._(jni$.JObject _$Countable) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/Countable');

  /// `package:jni` type descriptor for `com.example.fixtures.Countable`.
  static const jni$.JType<Countable> type = _$Countable$Type();

  static final _$m$size = _$class.instanceMethodId(r'size', r'()I');
  /// Native API: `com.example.fixtures.Countable#size()`
  ///
  /// - Android API: 1+
  int size() {
    return rt$.guardJni(() => _$m$size.call(this, jni$.jint.type, []));
  }

  static final Map<int, $Countable> _$impls = {};

  static jnii$.JObjectPtr _$invoke(int port, jnii$.JObjectPtr descriptor, jnii$.JObjectPtr args) {
    final $r = _$invokeMethod(port, jnii$.MethodInvocation.fromAddresses(0, descriptor.address, args.address));
    rt$.NativeCallbacks.wakeEventLoop();
    return $r;
  }

  static final jnii$.Pointer<jnii$.NativeFunction<jnii$.JObjectPtr Function(jnii$.Int64, jnii$.JObjectPtr, jnii$.JObjectPtr)>> _$invokePointer =
      jnii$.Pointer.fromFunction(_$invoke);

  static jnii$.Pointer<jnii$.Void> _$invokeMethod(int $p, jnii$.MethodInvocation $i) {
    final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
    if ($d == r'size()I') {
      try {
        final $r = _$impls[$p]!.size();
        return $r.toJInteger().reference.toPointer();
      } catch (e, st) {
        rt$.NativeCallbacks.reportPropagated(e, st, r'com.example.fixtures.Countable#size()');
        return jnii$.ProtectedJniExtensions.newDartException(e);
      }
    }
    return jnii$.nullptr;
  }

  /// Adds a Dart implementation of `com.example.fixtures.Countable` to [implementer], for
  /// objects implementing several interfaces.
  static void implementIn(jni$.JImplementer implementer, $Countable $impl) {
    late final jnii$.RawReceivePort $p;
    $p = jnii$.RawReceivePort((Object? $m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jnii$.MethodInvocation.fromMessage($m as List<dynamic>);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jnii$.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(r'com.example.fixtures.Countable', $p, _$invokePointer, [
    ]);
    _$impls[$p.sendPort.nativePort] = $impl;
  }

  /// Creates a Java object implementing `com.example.fixtures.Countable` backed by [$impl].
  ///
  /// The Dart implementation is retained until the Java proxy is
  /// garbage-collected. A `void` callback that throws is reported through
  /// `NativeCallbacks` instead of crashing the calling Java thread.
  factory Countable.implement($Countable $impl) {
    final $i = jni$.JImplementer();
    implementIn($i, $impl);
    return $i.implement<Countable>();
  }
}

final class _$Countable$Type extends jni$.JType<Countable> {
  const _$Countable$Type();

  @override
  String get signature => r'Lcom/example/fixtures/Countable;';
}

/// Dart implementation of `com.example.fixtures.Countable`; see [Countable.implement].
abstract base mixin class $Countable {
  factory $Countable({
    required int Function() size,
  }) = _$Countable;

  /// Implements `com.example.fixtures.Countable#size()`.
  int size();

}

final class _$Countable with $Countable {
  _$Countable({
    required int Function() size,
  }) : _size = size;

  final int Function() _size;
  @override
  int size() => _size();

}

/// Native API: `com.example.fixtures.DeprecatedClass` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
@Deprecated('Deprecated in the Android SDK')
extension type DeprecatedClass._(jni$.JObject _$DeprecatedClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/DeprecatedClass');

  /// `package:jni` type descriptor for `com.example.fixtures.DeprecatedClass`.
  static const jni$.JType<DeprecatedClass> type = _$DeprecatedClass$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.DeprecatedClass#<init>()`
  ///
  /// - Android API: 1+
  factory DeprecatedClass() {
    return rt$.guardJni(() => _$c$.call<DeprecatedClass>(_$class, []));
  }

  static final _$m$run = _$class.instanceMethodId(r'run', r'()V');
  /// Native API: `com.example.fixtures.DeprecatedClass#run()`
  ///
  /// - Android API: 1+
  void run() {
    rt$.guardJni(() => _$m$run.call(this, jni$.jvoid.type, []));
  }
}

final class _$DeprecatedClass$Type extends jni$.JType<DeprecatedClass> {
  const _$DeprecatedClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/DeprecatedClass;';
}

/// Native API: `com.example.fixtures.DualImpl` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
/// - Interfaces: `com.example.fixtures.Sizable`, `com.example.fixtures.Countable`, `com.example.fixtures.Marker`
extension type DualImpl._(jni$.JObject _$DualImpl) implements Sizable, Countable, Marker {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/DualImpl');

  /// `package:jni` type descriptor for `com.example.fixtures.DualImpl`.
  static const jni$.JType<DualImpl> type = _$DualImpl$Type();

  static final _$m$create = _$class.staticMethodId(r'create', r'(I)Lcom/example/fixtures/DualImpl;');
  /// Native API: `com.example.fixtures.DualImpl#create(int)`
  ///
  /// - Android API: 1+
  /// - Returns `com.example.fixtures.DualImpl`, nullability unknown (treated as nullable)
  static DualImpl? create(int n) {
    return rt$.guardJni(() => _$m$create.callNullable(_$class, DualImpl.type, [jni$.JValueInt(n)]));
  }

  static final _$m$size = _$class.instanceMethodId(r'size', r'()I');
  /// Native API: `com.example.fixtures.Countable#size()`
  ///
  /// - Android API: 1+
  // Redeclared: inherited from more than one supertype.
  int size() {
    return rt$.guardJni(() => _$m$size.call(this, jni$.jint.type, []));
  }
}

final class _$DualImpl$Type extends jni$.JType<DualImpl> {
  const _$DualImpl$Type();

  @override
  String get signature => r'Lcom/example/fixtures/DualImpl;';
}

/// Native API: `com.example.fixtures.EnumClass` (enum)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Enum<com.example.fixtures.EnumClass>`
extension type EnumClass._(jni$.JObject _$EnumClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/EnumClass');

  /// `package:jni` type descriptor for `com.example.fixtures.EnumClass`.
  static const jni$.JType<EnumClass> type = _$EnumClass$Type();

  static final _$f$FIRST = _$class.staticFieldId(r'FIRST', r'Lcom/example/fixtures/EnumClass;');
  /// Native API: `com.example.fixtures.EnumClass#FIRST`
  ///
  /// - Android API: 1+
  static EnumClass? get FIRST {
    return _$f$FIRST.getNullable(_$class, EnumClass.type);
  }

  static final _$f$SECOND = _$class.staticFieldId(r'SECOND', r'Lcom/example/fixtures/EnumClass;');
  /// Native API: `com.example.fixtures.EnumClass#SECOND`
  ///
  /// - Android API: 1+
  static EnumClass? get SECOND {
    return _$f$SECOND.getNullable(_$class, EnumClass.type);
  }

  static final _$m$code = _$class.instanceMethodId(r'code', r'()I');
  /// Native API: `com.example.fixtures.EnumClass#code()`
  ///
  /// - Android API: 1+
  int code() {
    return rt$.guardJni(() => _$m$code.call(this, jni$.jint.type, []));
  }

  static final _$m$valueOf = _$class.staticMethodId(r'valueOf', r'(Ljava/lang/String;)Lcom/example/fixtures/EnumClass;');
  /// Native API: `com.example.fixtures.EnumClass#valueOf(java.lang.String)`
  ///
  /// - Android API: 1+
  /// - `name`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Returns `com.example.fixtures.EnumClass`, nullability unknown (treated as nullable)
  static EnumClass? valueOf(String? name) {
    final _$name = name?.toJString();
    try {
      return rt$.guardJni(() => _$m$valueOf.callNullable(_$class, EnumClass.type, [_$name]));
    } finally {
      _$name?.release();
    }
  }

  static final _$m$values = _$class.staticMethodId(r'values', r'()[Lcom/example/fixtures/EnumClass;');
  /// Native API: `com.example.fixtures.EnumClass#values()`
  ///
  /// - Android API: 1+
  /// - Returns `com.example.fixtures.EnumClass[]`, nullability unknown (treated as nullable)
  static jni$.JArray<EnumClass?>? values() {
    return rt$.guardJni(() => _$m$values.callNullable(_$class, jni$.JArray.type<EnumClass?>(EnumClass.type), []));
  }
}

final class _$EnumClass$Type extends jni$.JType<EnumClass> {
  const _$EnumClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/EnumClass;';
}

/// Native API: `com.example.fixtures.GenericClass` (class)
///
/// - Android API: 1+
/// - Type parameters: `<T extends java.lang.CharSequence>` (erased)
/// - Superclass: `java.lang.Object`
/// - Note E003 UNSUPPORTED_GENERIC: Type parameters T are erased to their bounds
extension type GenericClass._(jni$.JObject _$GenericClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/GenericClass');

  /// `package:jni` type descriptor for `com.example.fixtures.GenericClass`.
  static const jni$.JType<GenericClass> type = _$GenericClass$Type();

  static final _$c$ = _$class.constructorId(r'(Ljava/lang/CharSequence;)V');
  /// Native API: `com.example.fixtures.GenericClass#<init>(java.lang.CharSequence)`
  ///
  /// - Android API: 1+
  /// - `value`: `T`, nullability unknown (treated as nullable)
  /// - Note E003 UNSUPPORTED_GENERIC: Generic types are erased to their bounds in this version
  factory GenericClass(jni$.JObject? value) {
    return rt$.guardJni(() => _$c$.call<GenericClass>(_$class, [value]));
  }

  static final _$m$first = _$class.instanceMethodId(r'first', r'(Ljava/util/List;)Ljava/lang/Object;');
  /// Native API: `com.example.fixtures.GenericClass#first(java.util.List)`
  ///
  /// - Android API: 1+
  /// - `items`: `java.util.List<E>`, nullability unknown (treated as nullable)
  /// - Returns `E`, nullability unknown (treated as nullable)
  /// - Note E003 UNSUPPORTED_GENERIC: Generic types are erased to their bounds in this version
  /// - Note E016 OUTSIDE_CLOSURE: Outside the generation closure, exposed as JObject: java.util.List
  jni$.JObject? first(jni$.JObject? items) {
    return rt$.guardJni(() => _$m$first.callNullable(this, jni$.JObject.type, [items]));
  }

  static final _$m$get = _$class.instanceMethodId(r'get', r'()Ljava/lang/CharSequence;');
  /// Native API: `com.example.fixtures.GenericClass#get()`
  ///
  /// - Android API: 1+
  /// - Returns `T`, nullability unknown (treated as nullable)
  /// - Note E003 UNSUPPORTED_GENERIC: Generic types are erased to their bounds in this version
  jni$.JObject? get() {
    return rt$.guardJni(() => _$m$get.callNullable(this, jni$.JObject.type, []));
  }

  static final _$m$index = _$class.staticMethodId(r'index', r'(Ljava/util/List;Ljava/util/List;)Ljava/util/Map;');
  /// Native API: `com.example.fixtures.GenericClass#index(java.util.List,java.util.List)`
  ///
  /// - Android API: 1+
  /// - `keys`: `java.util.List<? extends K>`, nullability unknown (treated as nullable)
  /// - `values`: `java.util.List<? super V>`, nullability unknown (treated as nullable)
  /// - Returns `java.util.Map<K, V>`, nullability unknown (treated as nullable)
  /// - Note E003 UNSUPPORTED_GENERIC: Generic types are erased to their bounds in this version
  /// - Note E016 OUTSIDE_CLOSURE: Outside the generation closure, exposed as JObject: java.util.List, java.util.Map
  static jni$.JObject? index(jni$.JObject? keys, jni$.JObject? values) {
    return rt$.guardJni(() => _$m$index.callNullable(_$class, jni$.JObject.type, [keys, values]));
  }

  static final _$m$set = _$class.instanceMethodId(r'set', r'(Ljava/lang/CharSequence;)V');
  /// Native API: `com.example.fixtures.GenericClass#set(java.lang.CharSequence)`
  ///
  /// - Android API: 1+
  /// - `value`: `T`, nullability unknown (treated as nullable)
  /// - Note E003 UNSUPPORTED_GENERIC: Generic types are erased to their bounds in this version
  void set(jni$.JObject? value) {
    rt$.guardJni(() => _$m$set.call(this, jni$.jvoid.type, [value]));
  }
}

final class _$GenericClass$Type extends jni$.JType<GenericClass> {
  const _$GenericClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/GenericClass;';
}

/// Native API: `com.example.fixtures.Marker` (interface)
///
/// - Android API: 1+
///
/// Implement in Dart with [Marker.implement].
extension type Marker._(jni$.JObject _$Marker) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/Marker');

  /// `package:jni` type descriptor for `com.example.fixtures.Marker`.
  static const jni$.JType<Marker> type = _$Marker$Type();
}

final class _$Marker$Type extends jni$.JType<Marker> {
  const _$Marker$Type();

  @override
  String get signature => r'Lcom/example/fixtures/Marker;';
}

/// Native API: `com.example.fixtures.MultiParent` (class)
///
/// - Android API: 1+
/// - Superclass: `com.example.fixtures.NestedClass`
/// - Interfaces: `java.lang.Comparable<com.example.fixtures.MultiParent>`, `com.example.fixtures.CallbackInterface`, `java.lang.Cloneable`
extension type MultiParent._(jni$.JObject _$MultiParent) implements NestedClass, CallbackInterface {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/MultiParent');

  /// `package:jni` type descriptor for `com.example.fixtures.MultiParent`.
  static const jni$.JType<MultiParent> type = _$MultiParent$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.MultiParent#<init>()`
  ///
  /// - Android API: 1+
  factory MultiParent() {
    return rt$.guardJni(() => _$c$.call<MultiParent>(_$class, []));
  }

  static final _$m$compareTo = _$class.instanceMethodId(r'compareTo', r'(Lcom/example/fixtures/MultiParent;)I');
  /// Native API: `com.example.fixtures.MultiParent#compareTo(com.example.fixtures.MultiParent)`
  ///
  /// - Android API: 1+
  /// - `other`: `com.example.fixtures.MultiParent`, nullability unknown (treated as nullable)
  int compareTo(MultiParent? other) {
    return rt$.guardJni(() => _$m$compareTo.call(this, jni$.jint.type, [other]));
  }

  static final _$m$onEvent = _$class.instanceMethodId(r'onEvent', r'(Ljava/lang/String;I)V');
  /// Native API: `com.example.fixtures.MultiParent#onEvent(java.lang.String,int)`
  ///
  /// - Android API: 1+
  /// - `name`: `java.lang.String`, nullability unknown (treated as nullable)
  void onEvent(String? name, int code) {
    final _$name = name?.toJString();
    try {
      rt$.guardJni(() => _$m$onEvent.call(this, jni$.jvoid.type, [_$name, jni$.JValueInt(code)]));
    } finally {
      _$name?.release();
    }
  }

  static final _$m$shouldContinue = _$class.instanceMethodId(r'shouldContinue', r'()Z');
  /// Native API: `com.example.fixtures.MultiParent#shouldContinue()`
  ///
  /// - Android API: 1+
  bool shouldContinue() {
    return rt$.guardJni(() => _$m$shouldContinue.call(this, jni$.jboolean.type, []));
  }
}

final class _$MultiParent$Type extends jni$.JType<MultiParent> {
  const _$MultiParent$Type();

  @override
  String get signature => r'Lcom/example/fixtures/MultiParent;';
}

/// Native API: `com.example.fixtures.NestedClass` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type NestedClass._(jni$.JObject _$NestedClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/NestedClass');

  /// `package:jni` type descriptor for `com.example.fixtures.NestedClass`.
  static const jni$.JType<NestedClass> type = _$NestedClass$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.NestedClass#<init>()`
  ///
  /// - Android API: 1+
  factory NestedClass() {
    return rt$.guardJni(() => _$c$.call<NestedClass>(_$class, []));
  }

  static final _$m$name = _$class.instanceMethodId(r'name', r'()Ljava/lang/String;');
  /// Native API: `com.example.fixtures.NestedClass#name()`
  ///
  /// - Android API: 1+
  /// - Returns `java.lang.String`, nullability unknown (treated as nullable)
  String? name() {
    return rt$.guardJni(() => _$m$name.callNullable(this, jni$.JString.type, [])?.toDartString(releaseOriginal: true));
  }
}

final class _$NestedClass$Type extends jni$.JType<NestedClass> {
  const _$NestedClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/NestedClass;';
}

/// Native API: `com.example.fixtures.NestedClass$Builder` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type NestedClass_Builder._(jni$.JObject _$NestedClass_Builder) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/NestedClass$Builder');

  /// `package:jni` type descriptor for `com.example.fixtures.NestedClass$Builder`.
  static const jni$.JType<NestedClass_Builder> type = _$NestedClass_Builder$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.NestedClass$Builder#<init>()`
  ///
  /// - Android API: 1+
  factory NestedClass_Builder() {
    return rt$.guardJni(() => _$c$.call<NestedClass_Builder>(_$class, []));
  }

  static final _$m$build = _$class.instanceMethodId(r'build', r'()Lcom/example/fixtures/NestedClass;');
  /// Native API: `com.example.fixtures.NestedClass$Builder#build()`
  ///
  /// - Android API: 1+
  /// - Returns `com.example.fixtures.NestedClass`, nullability unknown (treated as nullable)
  NestedClass? build() {
    return rt$.guardJni(() => _$m$build.callNullable(this, NestedClass.type, []));
  }

  static final _$m$name = _$class.instanceMethodId(r'name', r'(Ljava/lang/String;)Lcom/example/fixtures/NestedClass$Builder;');
  /// Native API: `com.example.fixtures.NestedClass$Builder#name(java.lang.String)`
  ///
  /// - Android API: 1+
  /// - `name`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Returns `com.example.fixtures.NestedClass$Builder`, nullability unknown (treated as nullable)
  NestedClass_Builder? name(String? name) {
    final _$name = name?.toJString();
    try {
      return rt$.guardJni(() => _$m$name.callNullable(this, NestedClass_Builder.type, [_$name]));
    } finally {
      _$name?.release();
    }
  }
}

final class _$NestedClass_Builder$Type extends jni$.JType<NestedClass_Builder> {
  const _$NestedClass_Builder$Type();

  @override
  String get signature => r'Lcom/example/fixtures/NestedClass$Builder;';
}

/// Native API: `com.example.fixtures.NestedClass$Inner` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type NestedClass_Inner._(jni$.JObject _$NestedClass_Inner) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/NestedClass$Inner');

  /// `package:jni` type descriptor for `com.example.fixtures.NestedClass$Inner`.
  static const jni$.JType<NestedClass_Inner> type = _$NestedClass_Inner$Type();

  static final _$c$ = _$class.constructorId(r'(Lcom/example/fixtures/NestedClass;)V');
  /// Native API: `com.example.fixtures.NestedClass$Inner#<init>(com.example.fixtures.NestedClass)`
  ///
  /// - Android API: 1+
  /// - `this$0`: `com.example.fixtures.NestedClass`, nullability unknown (treated as nullable)
  factory NestedClass_Inner(NestedClass? this$0) {
    return rt$.guardJni(() => _$c$.call<NestedClass_Inner>(_$class, [this$0]));
  }

  static final _$m$value = _$class.instanceMethodId(r'value', r'()I');
  /// Native API: `com.example.fixtures.NestedClass$Inner#value()`
  ///
  /// - Android API: 1+
  int value() {
    return rt$.guardJni(() => _$m$value.call(this, jni$.jint.type, []));
  }
}

final class _$NestedClass_Inner$Type extends jni$.JType<NestedClass_Inner> {
  const _$NestedClass_Inner$Type();

  @override
  String get signature => r'Lcom/example/fixtures/NestedClass$Inner;';
}

/// Native API: `com.example.fixtures.NestedClass$Listener` (interface)
///
/// - Android API: 1+
///
/// Implement in Dart with [NestedClass_Listener.implement].
extension type NestedClass_Listener._(jni$.JObject _$NestedClass_Listener) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/NestedClass$Listener');

  /// `package:jni` type descriptor for `com.example.fixtures.NestedClass$Listener`.
  static const jni$.JType<NestedClass_Listener> type = _$NestedClass_Listener$Type();

  static final _$m$onChange = _$class.instanceMethodId(r'onChange', r'(Lcom/example/fixtures/NestedClass;)V');
  /// Native API: `com.example.fixtures.NestedClass$Listener#onChange(com.example.fixtures.NestedClass)`
  ///
  /// - Android API: 1+
  /// - `p0`: `com.example.fixtures.NestedClass`, nullability unknown (treated as nullable)
  void onChange(NestedClass? p0) {
    rt$.guardJni(() => _$m$onChange.call(this, jni$.jvoid.type, [p0]));
  }

  static final Map<int, $NestedClass_Listener> _$impls = {};

  static jnii$.JObjectPtr _$invoke(int port, jnii$.JObjectPtr descriptor, jnii$.JObjectPtr args) {
    final $r = _$invokeMethod(port, jnii$.MethodInvocation.fromAddresses(0, descriptor.address, args.address));
    rt$.NativeCallbacks.wakeEventLoop();
    return $r;
  }

  static final jnii$.Pointer<jnii$.NativeFunction<jnii$.JObjectPtr Function(jnii$.Int64, jnii$.JObjectPtr, jnii$.JObjectPtr)>> _$invokePointer =
      jnii$.Pointer.fromFunction(_$invoke);

  static jnii$.Pointer<jnii$.Void> _$invokeMethod(int $p, jnii$.MethodInvocation $i) {
    final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
    final $a = $i.args;
    if ($d == r'onChange(Lcom/example/fixtures/NestedClass;)V') {
      try {
        _$impls[$p]!.onChange(($a![0] as NestedClass?));
        return jnii$.nullptr;
      } catch (e, st) {
        if (rt$.NativeCallbacks.handleVoidCallbackError(e, st, r'com.example.fixtures.NestedClass$Listener#onChange(com.example.fixtures.NestedClass)')) {
          return jnii$.nullptr;
        }
        return jnii$.ProtectedJniExtensions.newDartException(e);
      }
    }
    return jnii$.nullptr;
  }

  /// Adds a Dart implementation of `com.example.fixtures.NestedClass$Listener` to [implementer], for
  /// objects implementing several interfaces.
  static void implementIn(jni$.JImplementer implementer, $NestedClass_Listener $impl) {
    late final jnii$.RawReceivePort $p;
    $p = jnii$.RawReceivePort((Object? $m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jnii$.MethodInvocation.fromMessage($m as List<dynamic>);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jnii$.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(r'com.example.fixtures.NestedClass$Listener', $p, _$invokePointer, [
      if ($impl.onChange$async) r'onChange(Lcom/example/fixtures/NestedClass;)V',
    ]);
    _$impls[$p.sendPort.nativePort] = $impl;
  }

  /// Creates a Java object implementing `com.example.fixtures.NestedClass$Listener` backed by [$impl].
  ///
  /// The Dart implementation is retained until the Java proxy is
  /// garbage-collected. A `void` callback that throws is reported through
  /// `NativeCallbacks` instead of crashing the calling Java thread.
  factory NestedClass_Listener.implement($NestedClass_Listener $impl) {
    final $i = jni$.JImplementer();
    implementIn($i, $impl);
    return $i.implement<NestedClass_Listener>();
  }
}

final class _$NestedClass_Listener$Type extends jni$.JType<NestedClass_Listener> {
  const _$NestedClass_Listener$Type();

  @override
  String get signature => r'Lcom/example/fixtures/NestedClass$Listener;';
}

/// Dart implementation of `com.example.fixtures.NestedClass$Listener`; see [NestedClass_Listener.implement].
abstract base mixin class $NestedClass_Listener {
  factory $NestedClass_Listener({
    required void Function(NestedClass? p0) onChange,
    bool onChange$async,
  }) = _$NestedClass_Listener;

  /// Implements `com.example.fixtures.NestedClass$Listener#onChange(com.example.fixtures.NestedClass)`.
  void onChange(NestedClass? p0);

  /// Whether Java calls to [onChange] return without waiting for Dart.
  bool get onChange$async => false;

}

final class _$NestedClass_Listener with $NestedClass_Listener {
  _$NestedClass_Listener({
    required void Function(NestedClass? p0) onChange,
    this.onChange$async = false,
  }) : _onChange = onChange;

  final void Function(NestedClass? p0) _onChange;
  @override
  final bool onChange$async;
  @override
  void onChange(NestedClass? p0) => _onChange(p0);

}

/// Native API: `com.example.fixtures.NullableClass` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type NullableClass._(jni$.JObject _$NullableClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/NullableClass');

  /// `package:jni` type descriptor for `com.example.fixtures.NullableClass`.
  static const jni$.JType<NullableClass> type = _$NullableClass$Type();

  static final _$f$definitely = _$class.instanceFieldId(r'definitely', r'Ljava/lang/String;');
  /// Native API: `com.example.fixtures.NullableClass#definitely`
  ///
  /// - Android API: 1+
  String get definitely => _$f$definitely.get(this, jni$.JString.type).toDartString(releaseOriginal: true);
  set definitely(String value) { final j = value.toJString(); try { _$f$definitely.set(this, jni$.JString.type, j); } finally { j.release(); } }

  static final _$f$maybe = _$class.instanceFieldId(r'maybe', r'Ljava/lang/String;');
  /// Native API: `com.example.fixtures.NullableClass#maybe`
  ///
  /// - Android API: 1+
  String? get maybe => _$f$maybe.getNullable(this, jni$.JString.type)?.toDartString(releaseOriginal: true);
  set maybe(String? value) { final j = value?.toJString(); try { _$f$maybe.set(this, jni$.JString.type, j); } finally { j?.release(); } }

  static final _$f$unknown = _$class.instanceFieldId(r'unknown', r'Ljava/lang/String;');
  /// Native API: `com.example.fixtures.NullableClass#unknown`
  ///
  /// - Android API: 1+
  String? get unknown => _$f$unknown.getNullable(this, jni$.JString.type)?.toDartString(releaseOriginal: true);
  set unknown(String? value) { final j = value?.toJString(); try { _$f$unknown.set(this, jni$.JString.type, j); } finally { j?.release(); } }

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.NullableClass#<init>()`
  ///
  /// - Android API: 1+
  factory NullableClass() {
    return rt$.guardJni(() => _$c$.call<NullableClass>(_$class, []));
  }

  static final _$m$describe = _$class.instanceMethodId(r'describe', r'(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/String;');
  /// Native API: `com.example.fixtures.NullableClass#describe(java.lang.String,java.lang.Object,java.lang.String)`
  ///
  /// - Android API: 1+
  /// - `prefix`: `java.lang.String`, nullable
  /// - `value`: `java.lang.Object`, non-null
  /// - `unannotated`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Returns `java.lang.String`, non-null
  /// - Note E016 OUTSIDE_CLOSURE: Outside the generation closure, exposed as JObject: java.lang.Object
  String describe(String? prefix, jni$.JObject value, String? unannotated) {
    final _$prefix = prefix?.toJString();
    final _$unannotated = unannotated?.toJString();
    try {
      return rt$.guardJni(() => _$m$describe.call(this, jni$.JString.type, [_$prefix, value, _$unannotated]).toDartString(releaseOriginal: true));
    } finally {
      _$prefix?.release();
      _$unannotated?.release();
    }
  }

  static final _$m$find = _$class.staticMethodId(r'find', r'(Ljava/lang/String;)Lcom/example/fixtures/NullableClass;');
  /// Native API: `com.example.fixtures.NullableClass#find(java.lang.String)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, non-null
  /// - Returns `com.example.fixtures.NullableClass`, nullable
  static NullableClass? find(String key) {
    final _$key = key.toJString();
    try {
      return rt$.guardJni(() => _$m$find.callNullable(_$class, NullableClass.type, [_$key]));
    } finally {
      _$key.release();
    }
  }
}

final class _$NullableClass$Type extends jni$.JType<NullableClass> {
  const _$NullableClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/NullableClass;';
}

/// Native API: `com.example.fixtures.OverloadedClass` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type OverloadedClass._(jni$.JObject _$OverloadedClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/OverloadedClass');

  /// `package:jni` type descriptor for `com.example.fixtures.OverloadedClass`.
  static const jni$.JType<OverloadedClass> type = _$OverloadedClass$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.OverloadedClass#<init>()`
  ///
  /// - Android API: 1+
  factory OverloadedClass() {
    return rt$.guardJni(() => _$c$.call<OverloadedClass>(_$class, []));
  }

  static final _$c$new$int = _$class.constructorId(r'(I)V');
  /// Native API: `com.example.fixtures.OverloadedClass#<init>(int)`
  ///
  /// - Android API: 1+
  /// - Overload mapped to `OverloadedClass.new$int` (see binding_map.json)
  factory OverloadedClass.new$int(int value) {
    return rt$.guardJni(() => _$c$new$int.call<OverloadedClass>(_$class, [jni$.JValueInt(value)]));
  }

  static final _$c$new$String = _$class.constructorId(r'(Ljava/lang/String;)V');
  /// Native API: `com.example.fixtures.OverloadedClass#<init>(java.lang.String)`
  ///
  /// - Android API: 1+
  /// - `value`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.new$String` (see binding_map.json)
  factory OverloadedClass.new$String(String? value) {
    final _$value = value?.toJString();
    try {
      return rt$.guardJni(() => _$c$new$String.call<OverloadedClass>(_$class, [_$value]));
    } finally {
      _$value?.release();
    }
  }

  static final _$m$add = _$class.instanceMethodId(r'add', r'(II)I');
  /// Native API: `com.example.fixtures.OverloadedClass#add(int,int)`
  ///
  /// - Android API: 1+
  int add(int a, int b) {
    return rt$.guardJni(() => _$m$add.call(this, jni$.jint.type, [jni$.JValueInt(a), jni$.JValueInt(b)]));
  }

  static final _$m$add$String$String = _$class.instanceMethodId(r'add', r'(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;');
  /// Native API: `com.example.fixtures.OverloadedClass#add(java.lang.String,java.lang.String)`
  ///
  /// - Android API: 1+
  /// - `a`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - `b`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Returns `java.lang.String`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.add$String$String` (see binding_map.json)
  String? add$String$String(String? a, String? b) {
    final _$a = a?.toJString();
    final _$b = b?.toJString();
    try {
      return rt$.guardJni(() => _$m$add$String$String.callNullable(this, jni$.JString.type, [_$a, _$b])?.toDartString(releaseOriginal: true));
    } finally {
      _$a?.release();
      _$b?.release();
    }
  }

  static final _$m$add$double$double = _$class.instanceMethodId(r'add', r'(DD)D');
  /// Native API: `com.example.fixtures.OverloadedClass#add(double,double)`
  ///
  /// - Android API: 1+
  /// - Overload mapped to `OverloadedClass.add$double$double` (see binding_map.json)
  double add$double$double(double a, double b) {
    return rt$.guardJni(() => _$m$add$double$double.call(this, jni$.jdouble.type, [a, b]));
  }

  static final _$m$add$long$long = _$class.instanceMethodId(r'add', r'(JJ)J');
  /// Native API: `com.example.fixtures.OverloadedClass#add(long,long)`
  ///
  /// - Android API: 1+
  /// - Overload mapped to `OverloadedClass.add$long$long` (see binding_map.json)
  int add$long$long(int a, int b) {
    return rt$.guardJni(() => _$m$add$long$long.call(this, jni$.jlong.type, [a, b]));
  }

  static final _$m$join = _$class.staticMethodId(r'join', r'(Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;');
  /// Native API: `com.example.fixtures.OverloadedClass#join(java.lang.String,java.lang.String[])`
  ///
  /// - Android API: 1+
  /// - Varargs: pass the last argument as an array
  /// - `separator`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - `parts`: `java.lang.String[]`, nullability unknown (treated as nullable)
  /// - Returns `java.lang.String`, nullability unknown (treated as nullable)
  static String? join(String? separator, jni$.JArray<jni$.JString?>? parts) {
    final _$separator = separator?.toJString();
    try {
      return rt$.guardJni(() => _$m$join.callNullable(_$class, jni$.JString.type, [_$separator, parts])?.toDartString(releaseOriginal: true));
    } finally {
      _$separator?.release();
    }
  }

  static final _$m$last = _$class.instanceMethodId(r'last', r'()Ljava/lang/String;');
  /// Native API: `com.example.fixtures.OverloadedClass#last()`
  ///
  /// - Android API: 1+
  /// - Returns `java.lang.String`, nullability unknown (treated as nullable)
  String? last() {
    return rt$.guardJni(() => _$m$last.callNullable(this, jni$.JString.type, [])?.toDartString(releaseOriginal: true));
  }

  static final _$m$put = _$class.instanceMethodId(r'put', r'(Ljava/lang/String;I)V');
  /// Native API: `com.example.fixtures.OverloadedClass#put(java.lang.String,int)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  void put(String? key, int value) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$put.call(this, jni$.jvoid.type, [_$key, jni$.JValueInt(value)]));
    } finally {
      _$key?.release();
    }
  }

  static final _$m$put$String$String = _$class.instanceMethodId(r'put', r'(Ljava/lang/String;Ljava/lang/String;)V');
  /// Native API: `com.example.fixtures.OverloadedClass#put(java.lang.String,java.lang.String)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - `value`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.put$String$String` (see binding_map.json)
  void put$String$String(String? key, String? value) {
    final _$key = key?.toJString();
    final _$value = value?.toJString();
    try {
      rt$.guardJni(() => _$m$put$String$String.call(this, jni$.jvoid.type, [_$key, _$value]));
    } finally {
      _$key?.release();
      _$value?.release();
    }
  }

  static final _$m$put$String$boolean = _$class.instanceMethodId(r'put', r'(Ljava/lang/String;Z)V');
  /// Native API: `com.example.fixtures.OverloadedClass#put(java.lang.String,boolean)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.put$String$boolean` (see binding_map.json)
  void put$String$boolean(String? key, bool value) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$put$String$boolean.call(this, jni$.jvoid.type, [_$key, value]));
    } finally {
      _$key?.release();
    }
  }

  static final _$m$put$String$byte = _$class.instanceMethodId(r'put', r'(Ljava/lang/String;B)V');
  /// Native API: `com.example.fixtures.OverloadedClass#put(java.lang.String,byte)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.put$String$byte` (see binding_map.json)
  void put$String$byte(String? key, int value) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$put$String$byte.call(this, jni$.jvoid.type, [_$key, jni$.JValueByte(value)]));
    } finally {
      _$key?.release();
    }
  }

  static final _$m$put$String$char = _$class.instanceMethodId(r'put', r'(Ljava/lang/String;C)V');
  /// Native API: `com.example.fixtures.OverloadedClass#put(java.lang.String,char)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.put$String$char` (see binding_map.json)
  void put$String$char(String? key, int value) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$put$String$char.call(this, jni$.jvoid.type, [_$key, jni$.JValueChar(value)]));
    } finally {
      _$key?.release();
    }
  }

  static final _$m$put$String$float = _$class.instanceMethodId(r'put', r'(Ljava/lang/String;F)V');
  /// Native API: `com.example.fixtures.OverloadedClass#put(java.lang.String,float)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.put$String$float` (see binding_map.json)
  void put$String$float(String? key, double value) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$put$String$float.call(this, jni$.jvoid.type, [_$key, jni$.JValueFloat(value)]));
    } finally {
      _$key?.release();
    }
  }

  static final _$m$put$String$intArray = _$class.instanceMethodId(r'put', r'(Ljava/lang/String;[I)V');
  /// Native API: `com.example.fixtures.OverloadedClass#put(java.lang.String,int[])`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - `value`: `int[]`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.put$String$intArray` (see binding_map.json)
  void put$String$intArray(String? key, jni$.JIntArray? value) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$put$String$intArray.call(this, jni$.jvoid.type, [_$key, value]));
    } finally {
      _$key?.release();
    }
  }

  static final _$m$put$String$short = _$class.instanceMethodId(r'put', r'(Ljava/lang/String;S)V');
  /// Native API: `com.example.fixtures.OverloadedClass#put(java.lang.String,short)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Overload mapped to `OverloadedClass.put$String$short` (see binding_map.json)
  void put$String$short(String? key, int value) {
    final _$key = key?.toJString();
    try {
      rt$.guardJni(() => _$m$put$String$short.call(this, jni$.jvoid.type, [_$key, jni$.JValueShort(value)]));
    } finally {
      _$key?.release();
    }
  }
}

final class _$OverloadedClass$Type extends jni$.JType<OverloadedClass> {
  const _$OverloadedClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/OverloadedClass;';
}

/// Native API: `com.example.fixtures.ReservedWords` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type ReservedWords._(jni$.JObject _$ReservedWords) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/ReservedWords');

  /// `package:jni` type descriptor for `com.example.fixtures.ReservedWords`.
  static const jni$.JType<ReservedWords> type = _$ReservedWords$Type();

  /// Native API: `com.example.fixtures.ReservedWords#in`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `1`
  static const int in$ = 1;

  /// Native API: `com.example.fixtures.ReservedWords#is`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `2`
  static const int is$ = 2;

  /// Native API: `com.example.fixtures.ReservedWords#type`
  ///
  /// - Android API: 1+
  /// - Constant value (inlined from the SDK): `3`
  static const int type$ = 3;

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.ReservedWords#<init>()`
  ///
  /// - Android API: 1+
  factory ReservedWords() {
    return rt$.guardJni(() => _$c$.call<ReservedWords>(_$class, []));
  }

  static final _$m$equals = _$class.instanceMethodId(r'equals', r'(Ljava/lang/Object;)Z');
  /// Native API: `com.example.fixtures.ReservedWords#equals(java.lang.Object)`
  ///
  /// - Android API: 1+
  /// - `other`: `java.lang.Object`, nullability unknown (treated as nullable)
  /// - Note E016 OUTSIDE_CLOSURE: Outside the generation closure, exposed as JObject: java.lang.Object
  bool equals(jni$.JObject? other) {
    return rt$.guardJni(() => _$m$equals.call(this, jni$.jboolean.type, [other]));
  }

  static final _$m$get = _$class.instanceMethodId(r'get', r'(III)V');
  /// Native API: `com.example.fixtures.ReservedWords#get(int,int,int)`
  ///
  /// - Android API: 1+
  void get(int extension, int switch_, int with$) {
    rt$.guardJni(() => _$m$get.call(this, jni$.jvoid.type, [jni$.JValueInt(extension), jni$.JValueInt(switch_), jni$.JValueInt(with$)]));
  }

  static final _$m$hashCode$ = _$class.instanceMethodId(r'hashCode', r'()I');
  /// Native API: `com.example.fixtures.ReservedWords#hashCode()`
  ///
  /// - Android API: 1+
  int hashCode$() {
    return rt$.guardJni(() => _$m$hashCode$.call(this, jni$.jint.type, []));
  }

  static final _$m$late = _$class.staticMethodId(r'late', r'(I)V');
  /// Native API: `com.example.fixtures.ReservedWords#late(int)`
  ///
  /// - Android API: 1+
  static void late(int required) {
    rt$.guardJni(() => _$m$late.call(_$class, jni$.jvoid.type, [jni$.JValueInt(required)]));
  }

  static final _$m$release$ = _$class.instanceMethodId(r'release', r'()V');
  /// Native API: `com.example.fixtures.ReservedWords#release()`
  ///
  /// - Android API: 1+
  void release$() {
    rt$.guardJni(() => _$m$release$.call(this, jni$.jvoid.type, []));
  }

  static final _$m$toString$ = _$class.instanceMethodId(r'toString', r'()Ljava/lang/String;');
  /// Native API: `com.example.fixtures.ReservedWords#toString()`
  ///
  /// - Android API: 1+
  /// - Returns `java.lang.String`, nullability unknown (treated as nullable)
  String? toString$() {
    return rt$.guardJni(() => _$m$toString$.callNullable(this, jni$.JString.type, [])?.toDartString(releaseOriginal: true));
  }

  static final _$m$yield = _$class.instanceMethodId(r'yield', r'()V');
  /// Native API: `com.example.fixtures.ReservedWords#yield()`
  ///
  /// - Android API: 1+
  void yield() {
    rt$.guardJni(() => _$m$yield.call(this, jni$.jvoid.type, []));
  }
}

final class _$ReservedWords$Type extends jni$.JType<ReservedWords> {
  const _$ReservedWords$Type();

  @override
  String get signature => r'Lcom/example/fixtures/ReservedWords;';
}

/// Native API: `com.example.fixtures.Sizable` (interface)
///
/// - Android API: 1+
///
/// Implement in Dart with [Sizable.implement].
extension type Sizable._(jni$.JObject _$Sizable) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/Sizable');

  /// `package:jni` type descriptor for `com.example.fixtures.Sizable`.
  static const jni$.JType<Sizable> type = _$Sizable$Type();

  static final _$m$size = _$class.instanceMethodId(r'size', r'()I');
  /// Native API: `com.example.fixtures.Sizable#size()`
  ///
  /// - Android API: 1+
  int size() {
    return rt$.guardJni(() => _$m$size.call(this, jni$.jint.type, []));
  }

  static final Map<int, $Sizable> _$impls = {};

  static jnii$.JObjectPtr _$invoke(int port, jnii$.JObjectPtr descriptor, jnii$.JObjectPtr args) {
    final $r = _$invokeMethod(port, jnii$.MethodInvocation.fromAddresses(0, descriptor.address, args.address));
    rt$.NativeCallbacks.wakeEventLoop();
    return $r;
  }

  static final jnii$.Pointer<jnii$.NativeFunction<jnii$.JObjectPtr Function(jnii$.Int64, jnii$.JObjectPtr, jnii$.JObjectPtr)>> _$invokePointer =
      jnii$.Pointer.fromFunction(_$invoke);

  static jnii$.Pointer<jnii$.Void> _$invokeMethod(int $p, jnii$.MethodInvocation $i) {
    final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
    if ($d == r'size()I') {
      try {
        final $r = _$impls[$p]!.size();
        return $r.toJInteger().reference.toPointer();
      } catch (e, st) {
        rt$.NativeCallbacks.reportPropagated(e, st, r'com.example.fixtures.Sizable#size()');
        return jnii$.ProtectedJniExtensions.newDartException(e);
      }
    }
    return jnii$.nullptr;
  }

  /// Adds a Dart implementation of `com.example.fixtures.Sizable` to [implementer], for
  /// objects implementing several interfaces.
  static void implementIn(jni$.JImplementer implementer, $Sizable $impl) {
    late final jnii$.RawReceivePort $p;
    $p = jnii$.RawReceivePort((Object? $m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jnii$.MethodInvocation.fromMessage($m as List<dynamic>);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jnii$.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(r'com.example.fixtures.Sizable', $p, _$invokePointer, [
    ]);
    _$impls[$p.sendPort.nativePort] = $impl;
  }

  /// Creates a Java object implementing `com.example.fixtures.Sizable` backed by [$impl].
  ///
  /// The Dart implementation is retained until the Java proxy is
  /// garbage-collected. A `void` callback that throws is reported through
  /// `NativeCallbacks` instead of crashing the calling Java thread.
  factory Sizable.implement($Sizable $impl) {
    final $i = jni$.JImplementer();
    implementIn($i, $impl);
    return $i.implement<Sizable>();
  }
}

final class _$Sizable$Type extends jni$.JType<Sizable> {
  const _$Sizable$Type();

  @override
  String get signature => r'Lcom/example/fixtures/Sizable;';
}

/// Dart implementation of `com.example.fixtures.Sizable`; see [Sizable.implement].
abstract base mixin class $Sizable {
  factory $Sizable({
    required int Function() size,
  }) = _$Sizable;

  /// Implements `com.example.fixtures.Sizable#size()`.
  int size();

}

final class _$Sizable with $Sizable {
  _$Sizable({
    required int Function() size,
  }) : _size = size;

  final int Function() _size;
  @override
  int size() => _size();

}

/// Native API: `com.example.fixtures.SuspendShaped` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type SuspendShaped._(jni$.JObject _$SuspendShaped) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/SuspendShaped');

  /// `package:jni` type descriptor for `com.example.fixtures.SuspendShaped`.
  static const jni$.JType<SuspendShaped> type = _$SuspendShaped$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.SuspendShaped#<init>()`
  ///
  /// - Android API: 1+
  factory SuspendShaped() {
    return rt$.guardJni(() => _$c$.call<SuspendShaped>(_$class, []));
  }

  static final _$m$count = _$class.instanceMethodId(r'count', r'(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;');
  /// Native API: `com.example.fixtures.SuspendShaped#count(kotlin.coroutines.Continuation)`
  ///
  /// - Android API: 1+
  /// - Kotlin `suspend` function: completes with `java.lang.Integer` (nullability not recorded in the JVM signature; treated as nullable)
  Future<int?> count() async {
    final $r = await rt$.callSuspend(($c) => _$m$count.callNullable(this, jni$.JObject.type, [$c]));
    return $r?.as(jni$.JInteger.type, releaseOriginal: true).toDartInt(releaseOriginal: true);
  }

  static final _$m$load = _$class.instanceMethodId(r'load', r'(Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;');
  /// Native API: `com.example.fixtures.SuspendShaped#load(java.lang.String,kotlin.coroutines.Continuation)`
  ///
  /// - Android API: 1+
  /// - `key`: `java.lang.String`, nullability unknown (treated as nullable)
  /// - Kotlin `suspend` function: completes with `java.lang.String` (nullability not recorded in the JVM signature; treated as nullable)
  Future<String?> load(String? key) async {
    final _$key = key?.toJString();
    try {
      final $r = await rt$.callSuspend(($c) => _$m$load.callNullable(this, jni$.JObject.type, [_$key, $c]));
      return $r?.as(jni$.JString.type, releaseOriginal: true).toDartString(releaseOriginal: true);
    } finally {
      _$key?.release();
    }
  }
}

final class _$SuspendShaped$Type extends jni$.JType<SuspendShaped> {
  const _$SuspendShaped$Type();

  @override
  String get signature => r'Lcom/example/fixtures/SuspendShaped;';
}

/// Native API: `com.example.fixtures.ThrowsClass` (class)
///
/// - Android API: 1+
/// - Superclass: `java.lang.Object`
extension type ThrowsClass._(jni$.JObject _$ThrowsClass) implements jni$.JObject {
  static final _$class = jni$.JClass.forName(r'com/example/fixtures/ThrowsClass');

  /// `package:jni` type descriptor for `com.example.fixtures.ThrowsClass`.
  static const jni$.JType<ThrowsClass> type = _$ThrowsClass$Type();

  static final _$c$ = _$class.constructorId(r'()V');
  /// Native API: `com.example.fixtures.ThrowsClass#<init>()`
  ///
  /// - Android API: 1+
  factory ThrowsClass() {
    return rt$.guardJni(() => _$c$.call<ThrowsClass>(_$class, []));
  }

  static final _$m$parse = _$class.staticMethodId(r'parse', r'(Ljava/lang/String;)I');
  /// Native API: `com.example.fixtures.ThrowsClass#parse(java.lang.String)`
  ///
  /// - Android API: 1+
  /// - Throws (Java): `java.lang.NumberFormatException`, `java.lang.IllegalStateException`; surfaced as `NativeJavaException`
  /// - `text`: `java.lang.String`, nullability unknown (treated as nullable)
  static int parse(String? text) {
    final _$text = text?.toJString();
    try {
      return rt$.guardJni(() => _$m$parse.call(_$class, jni$.jint.type, [_$text]));
    } finally {
      _$text?.release();
    }
  }

  static final _$m$read = _$class.instanceMethodId(r'read', r'()V');
  /// Native API: `com.example.fixtures.ThrowsClass#read()`
  ///
  /// - Android API: 1+
  /// - Throws (Java): `java.io.IOException`; surfaced as `NativeJavaException`
  void read() {
    rt$.guardJni(() => _$m$read.call(this, jni$.jvoid.type, []));
  }
}

final class _$ThrowsClass$Type extends jni$.JType<ThrowsClass> {
  const _$ThrowsClass$Type();

  @override
  String get signature => r'Lcom/example/fixtures/ThrowsClass;';
}
