import 'dart:io';
import 'dart:typed_data';

import 'package:native_api_core/native_api_core.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

/// Restricted-artifact fixtures are synthesised at test time (never committed)
/// so the repository itself stays clean under `audit-license`.
void main() {
  late Directory tmp;
  setUp(() => tmp = Directory.systemTemp.createTempSync('audit'));
  tearDown(() => tmp.deleteSync(recursive: true));

  void write(String rel, Object content) {
    final f = File(p.join(tmp.path, rel))..createSync(recursive: true);
    content is String
        ? f.writeAsStringSync(content)
        : f.writeAsBytesSync(content as List<int>);
  }

  Map<String, AuditStatus> rules(AuditReport r) => {
    for (final f in r.findings) '${f.subject}:${f.rule}': f.status,
  };

  final auditor = LicenseAuditor(pubCache: '/nonexistent');

  test('clean project passes', () {
    write('lib/a.dart', 'void main() {}\n');
    write('README.md', '# hi\n');
    final r = auditor.audit(tmp.path);
    expect(r.status, AuditStatus.pass);
    expect(r.filesScanned, 2);
  });

  test('blocks Mach-O, fat Mach-O and class files by content, not name', () {
    write(
      'bin/thing.dat',
      Uint8List.fromList([0xCF, 0xFA, 0xED, 0xFE, 7, 0, 0, 1, 0, 0]),
    );
    write(
      'bin/fat.bin',
      Uint8List.fromList([0xCA, 0xFE, 0xBA, 0xBE, 0, 0, 0, 2, 0, 0]),
    );
    write(
      'lib/Foo.txt',
      Uint8List.fromList([0xCA, 0xFE, 0xBA, 0xBE, 0, 0, 0, 52, 0, 0]),
    );
    final r = rules(auditor.audit(tmp.path));
    expect(r['bin/thing.dat:mach-o-binary'], AuditStatus.block);
    expect(r['bin/fat.bin:mach-o-binary'], AuditStatus.block);
    expect(r['lib/Foo.txt:jvm-class-file'], AuditStatus.block);
  });

  test('blocks framework bundles, SDK headers, tbd stubs, android.jar', () {
    write('ios/UIKit.framework/Headers/UIView.h', 'int x;\n');
    write(
      'vendor_headers/NSObject.h',
      '//\n//  NSObject.h\n//  Copyright (c) 1994-2024, Apple Inc. All rights reserved.\n//\n',
    );
    write('libs/libobjc.tbd', '--- !tapi-tbd\ntbd-version: 4\n');
    write(
      'libs/android.jar',
      Uint8List.fromList([0x50, 0x4B, 0x03, 0x04, 0, 0, 0, 0, 0, 0]),
    );
    final report = auditor.audit(tmp.path);
    final r = rules(report);
    expect(
      r['ios/UIKit.framework/Headers/UIView.h:apple-framework-bundle'],
      AuditStatus.block,
    );
    expect(r['vendor_headers/NSObject.h:apple-sdk-header'], AuditStatus.block);
    expect(r['libs/libobjc.tbd:apple-sdk-stub'], AuditStatus.block);
    expect(r['libs/android.jar:android-sdk-jar'], AuditStatus.block);
    expect(report.status, AuditStatus.block);
  });

  test('flags copied docs, third-party headers, generated SDK bindings', () {
    write(
      'docs/intent.html',
      '<html>Content and code samples on this page are subject to the licenses described in the Content License</html>',
    );
    write(
      'lib/x.java',
      '/*\n * Copyright (C) 2006 The Android Open Source Project\n */\nclass X {}\n',
    );
    write(
      'lib/y.ts',
      '// SPDX-License-'
          'Identifier: GPL-3.0\nexport {};\n',
    );
    write(
      'lib/gen.dart',
      '// GENERATED CODE - DO NOT MODIFY BY HAND.\n// Generated by native-api-bindgen 0.1.0\n// Source SDK: Android API 36\n',
    );
    write('third_party/foo/a.c', 'int a;\n');
    write(
      'lib/sdk.dart',
      "const p = '/Applications/Xcode.app/Contents/"
          "Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/';\n",
    );
    final r = rules(auditor.audit(tmp.path));
    expect(r['docs/intent.html:copied-platform-docs'], AuditStatus.block);
    expect(
      r['lib/x.java:third-party-license-header'],
      AuditStatus.reviewRequired,
    );
    expect(r['lib/y.ts:foreign-spdx'], AuditStatus.reviewRequired);
    expect(r['lib/gen.dart:generated-sdk-binding'], AuditStatus.warn);
    expect(
      r['third_party/foo/a.c:unknown-third-party'],
      AuditStatus.reviewRequired,
    );
    expect(r['lib/sdk.dart:xcode-sdk-path'], AuditStatus.warn);
  });

  test('dependency licenses are read offline and never assumed', () {
    final cache = Directory(p.join(tmp.path, 'cache'))..createSync();
    void lic(String dir, String text) => (File(
      p.join(cache.path, 'hosted', 'pub.dev', dir, 'LICENSE'),
    )..createSync(recursive: true)).writeAsStringSync(text);
    lic(
      'good-1.0.0',
      'Redistribution and use in source and binary forms ... Neither the name of',
    );
    lic('odd-2.0.0', 'All rights reserved. Ask us.');
    write('app/pubspec.lock', '''
packages:
  good:
    dependency: direct
    description: {name: good, url: "https://pub.dev"}
    source: hosted
    version: "1.0.0"
  odd:
    dependency: direct
    description: {name: odd, url: "https://pub.dev"}
    source: hosted
    version: "2.0.0"
  missing:
    dependency: direct
    description: {name: missing, url: "https://pub.dev"}
    source: hosted
    version: "3.0.0"
  flutter:
    dependency: direct
    description: flutter
    source: sdk
    version: "0.0.0"
''');
    final report = LicenseAuditor(pubCache: cache.path).audit(tmp.path);
    final deps = {for (final d in report.dependencies) d.name: d};
    expect(deps['good']!.license, 'BSD-3-Clause');
    expect(deps['good']!.status, AuditStatus.pass);
    expect(deps['odd']!.status, AuditStatus.reviewRequired);
    expect(deps['missing']!.status, AuditStatus.reviewRequired);
    expect(deps['flutter']!.status, AuditStatus.pass);
    expect(report.status, AuditStatus.reviewRequired);
  });

  test('allowlist waives reviewed files only when the checksum matches', () {
    write(
      'tools/wrapper.jar',
      Uint8List.fromList([0x50, 0x4B, 0x03, 0x04, 1, 2, 3, 4, 5, 6]),
    );
    write('ios/Foo.framework/x.h', 'int x;\n');
    const sha =
        'f1f1ae6e3c3c0f3c3d3e6b1c0d4c8bbd2c96f3bc3b5d7b2b5d3c2e7b0f2b1c4a';
    write(LicenseAuditor.allowlistFile, '''
entries:
  - path: tools/wrapper.jar
    sha256: $sha
    license: Apache-2.0
    justification: test
  - path: ios/Foo.framework/x.h
    sha256: $sha
    license: x
    justification: cannot waive BLOCK
''');
    var r = rules(auditor.audit(tmp.path));
    expect(r['tools/wrapper.jar:allowlist-mismatch'], AuditStatus.block);
    final real = LicenseAuditor.sha256Of(
      File(p.join(tmp.path, 'tools/wrapper.jar')),
    );
    write(LicenseAuditor.allowlistFile, '''
entries:
  - path: tools/wrapper.jar
    sha256: $real
    license: Apache-2.0
    justification: reviewed
''');
    r = rules(auditor.audit(tmp.path));
    expect(r.keys.where((k) => k.startsWith('tools/wrapper.jar')), isEmpty);
    expect(
      r['ios/Foo.framework/x.h:apple-framework-bundle'],
      AuditStatus.block,
    );
  });

  test('license text classification', () {
    expect(
      classifyLicenseText('Apache License\n Version 2.0, January 2004'),
      'Apache-2.0',
    );
    expect(
      classifyLicenseText(
        'Permission is hereby granted, free of charge, to any',
      ),
      'MIT',
    );
    expect(classifyLicenseText('GNU GENERAL PUBLIC LICENSE Version 3'), 'GPL');
    expect(classifyLicenseText('whatever'), 'UNKNOWN');
  });
}
